// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SQL_AuToHomes_ST7789-V3

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);

    ui_Panel3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel3, 278);
    lv_obj_set_height(ui_Panel3, 350);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 56);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel3, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_radius(ui_Panel3, 46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -150);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "전원 공급 시 자동 켜짐 기능 ");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 120);
    lv_obj_set_height(ui_Container1, 30);
    lv_obj_set_x(ui_Container1, -65);
    lv_obj_set_y(ui_Container1, 40);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch1 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_onSwitch1, 50);
    lv_obj_set_height(ui_onSwitch1, 25);
    lv_obj_set_x(ui_onSwitch1, 20);
    lv_obj_set_y(ui_onSwitch1, 0);
    lv_obj_set_align(ui_onSwitch1, LV_ALIGN_CENTER);


    ui_Label16 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -40);
    lv_obj_set_y(ui_Label16, 0);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "전체등");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 120);
    lv_obj_set_height(ui_Container2, 30);
    lv_obj_set_x(ui_Container2, 65);
    lv_obj_set_y(ui_Container2, 40);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch2 = lv_switch_create(ui_Container2);
    lv_obj_set_width(ui_onSwitch2, 50);
    lv_obj_set_height(ui_onSwitch2, 25);
    lv_obj_set_x(ui_onSwitch2, 20);
    lv_obj_set_y(ui_onSwitch2, 0);
    lv_obj_set_align(ui_onSwitch2, LV_ALIGN_CENTER);


    ui_Label17 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -40);
    lv_obj_set_y(ui_Label17, 0);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "실내등");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 120);
    lv_obj_set_height(ui_Container3, 30);
    lv_obj_set_x(ui_Container3, -65);
    lv_obj_set_y(ui_Container3, 80);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch3 = lv_switch_create(ui_Container3);
    lv_obj_set_width(ui_onSwitch3, 50);
    lv_obj_set_height(ui_onSwitch3, 25);
    lv_obj_set_x(ui_onSwitch3, 20);
    lv_obj_set_y(ui_onSwitch3, 0);
    lv_obj_set_align(ui_onSwitch3, LV_ALIGN_CENTER);


    ui_Label18 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -40);
    lv_obj_set_y(ui_Label18, 0);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "사이드");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 120);
    lv_obj_set_height(ui_Container4, 30);
    lv_obj_set_x(ui_Container4, 65);
    lv_obj_set_y(ui_Container4, 80);
    lv_obj_set_align(ui_Container4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch4 = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_onSwitch4, 50);
    lv_obj_set_height(ui_onSwitch4, 25);
    lv_obj_set_x(ui_onSwitch4, 20);
    lv_obj_set_y(ui_onSwitch4, 0);
    lv_obj_set_align(ui_onSwitch4, LV_ALIGN_CENTER);


    ui_Label19 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -40);
    lv_obj_set_y(ui_Label19, 0);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "팝업등");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 120);
    lv_obj_set_height(ui_Container5, 30);
    lv_obj_set_x(ui_Container5, -65);
    lv_obj_set_y(ui_Container5, 120);
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch5 = lv_switch_create(ui_Container5);
    lv_obj_set_width(ui_onSwitch5, 50);
    lv_obj_set_height(ui_onSwitch5, 25);
    lv_obj_set_x(ui_onSwitch5, 20);
    lv_obj_set_y(ui_onSwitch5, 0);
    lv_obj_set_align(ui_onSwitch5, LV_ALIGN_CENTER);


    ui_Label20 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label20, 58);
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -69);
    lv_obj_set_y(ui_Label20, 0);
    lv_obj_set_align(ui_Label20, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label20, "시트열선");
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 120);
    lv_obj_set_height(ui_Container6, 30);
    lv_obj_set_x(ui_Container6, 65);
    lv_obj_set_y(ui_Container6, 120);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch6 = lv_switch_create(ui_Container6);
    lv_obj_set_width(ui_onSwitch6, 50);
    lv_obj_set_height(ui_onSwitch6, 25);
    lv_obj_set_x(ui_onSwitch6, 20);
    lv_obj_set_y(ui_onSwitch6, 0);
    lv_obj_set_align(ui_onSwitch6, LV_ALIGN_CENTER);


    ui_Label21 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -40);
    lv_obj_set_y(ui_Label21, 0);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "무드등");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 120);
    lv_obj_set_height(ui_Container7, 30);
    lv_obj_set_x(ui_Container7, -65);
    lv_obj_set_y(ui_Container7, 160);
    lv_obj_set_align(ui_Container7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch7 = lv_switch_create(ui_Container7);
    lv_obj_set_width(ui_onSwitch7, 50);
    lv_obj_set_height(ui_onSwitch7, 25);
    lv_obj_set_x(ui_onSwitch7, 20);
    lv_obj_set_y(ui_onSwitch7, 0);
    lv_obj_set_align(ui_onSwitch7, LV_ALIGN_CENTER);


    ui_Label22 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -40);
    lv_obj_set_y(ui_Label22, 0);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "후면등");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 120);
    lv_obj_set_height(ui_Container8, 30);
    lv_obj_set_x(ui_Container8, 65);
    lv_obj_set_y(ui_Container8, 160);
    lv_obj_set_align(ui_Container8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch8 = lv_switch_create(ui_Container8);
    lv_obj_set_width(ui_onSwitch8, 50);
    lv_obj_set_height(ui_onSwitch8, 25);
    lv_obj_set_x(ui_onSwitch8, 20);
    lv_obj_set_y(ui_onSwitch8, 0);
    lv_obj_set_align(ui_onSwitch8, LV_ALIGN_CENTER);


    ui_Label23 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -40);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "어닝등");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 120);
    lv_obj_set_height(ui_Container9, 30);
    lv_obj_set_x(ui_Container9, 65);
    lv_obj_set_y(ui_Container9, 200);
    lv_obj_set_align(ui_Container9, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch10 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_onSwitch10, 50);
    lv_obj_set_height(ui_onSwitch10, 25);
    lv_obj_set_x(ui_onSwitch10, 20);
    lv_obj_set_y(ui_onSwitch10, 0);
    lv_obj_set_align(ui_onSwitch10, LV_ALIGN_CENTER);


    ui_Label24 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -40);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "TV");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 120);
    lv_obj_set_height(ui_Container10, 30);
    lv_obj_set_x(ui_Container10, -65);
    lv_obj_set_y(ui_Container10, 240);
    lv_obj_set_align(ui_Container10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch11 = lv_switch_create(ui_Container10);
    lv_obj_set_width(ui_onSwitch11, 50);
    lv_obj_set_height(ui_onSwitch11, 25);
    lv_obj_set_x(ui_onSwitch11, 20);
    lv_obj_set_y(ui_onSwitch11, 0);
    lv_obj_set_align(ui_onSwitch11, LV_ALIGN_CENTER);


    ui_Label25 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -40);
    lv_obj_set_y(ui_Label25, 0);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "냉장고");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button4, 80);
    lv_obj_set_height(ui_Button4, 40);
    lv_obj_set_x(ui_Button4, -60);
    lv_obj_set_y(ui_Button4, 145);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button4, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "저장 ");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button5, 80);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 60);
    lv_obj_set_y(ui_Button5, 145);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "취소");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 120);
    lv_obj_set_height(ui_Container11, 30);
    lv_obj_set_x(ui_Container11, 65);
    lv_obj_set_y(ui_Container11, 240);
    lv_obj_set_align(ui_Container11, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch12 = lv_switch_create(ui_Container11);
    lv_obj_set_width(ui_onSwitch12, 50);
    lv_obj_set_height(ui_onSwitch12, 25);
    lv_obj_set_x(ui_onSwitch12, 20);
    lv_obj_set_y(ui_onSwitch12, 0);
    lv_obj_set_align(ui_onSwitch12, LV_ALIGN_CENTER);


    ui_Label28 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -40);
    lv_obj_set_y(ui_Label28, 0);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "인버터");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 120);
    lv_obj_set_height(ui_Container12, 30);
    lv_obj_set_x(ui_Container12, -65);
    lv_obj_set_y(ui_Container12, 200);
    lv_obj_set_align(ui_Container12, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onSwitch9 = lv_switch_create(ui_Container12);
    lv_obj_set_width(ui_onSwitch9, 50);
    lv_obj_set_height(ui_onSwitch9, 25);
    lv_obj_set_x(ui_onSwitch9, 20);
    lv_obj_set_y(ui_onSwitch9, 0);
    lv_obj_set_align(ui_onSwitch9, LV_ALIGN_CENTER);


    ui_Label29 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -40);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "물펌프");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}
