// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_LM_SEAT_SC01-PLUS

#include "ui.h"

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_add_state(ui_ScreenHome, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image8, &ui_img_1622885619);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 447
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 149
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 83);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 200);

    ui_Container1 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 480);
    lv_obj_set_height(ui_Container1, 30);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -145);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image1, &ui_img_1332874776);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -163);
    lv_obj_set_y(ui_Image1, -1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 150);

    ui_ImageNetwork = lv_img_create(ui_Container1);
    lv_img_set_src(ui_ImageNetwork, &ui_img_420585491);
    lv_obj_set_width(ui_ImageNetwork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageNetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageNetwork, 215);
    lv_obj_set_y(ui_ImageNetwork, 0);
    lv_obj_set_align(ui_ImageNetwork, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImageNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageNetwork, 250);

    ui_Button1 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 120);
    lv_obj_set_x(ui_Button1, -172);
    lv_obj_set_y(ui_Button1, -58);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image4 = lv_img_create(ui_Button1);
    lv_img_set_src(ui_Image4, &ui_img_1285933598);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_img_set_zoom(ui_Image4, 180);

    ui_Button2 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 120);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -58);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image3 = lv_img_create(ui_Button2);
    lv_img_set_src(ui_Image3, &ui_img_149442631);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 180);

    ui_Button3 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 120);
    lv_obj_set_x(ui_Button3, 172);
    lv_obj_set_y(ui_Button3, -58);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image5 = lv_img_create(ui_Button3);
    lv_img_set_src(ui_Image5, &ui_img_932286548);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 180);

    ui_Button4 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 120);
    lv_obj_set_x(ui_Button4, -172);
    lv_obj_set_y(ui_Button4, 88);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Button4);
    lv_img_set_src(ui_Image7, &ui_img_1371686955);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -17);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 180);

    ui_ContainerL3 = lv_obj_create(ui_Button4);
    lv_obj_remove_style_all(ui_ContainerL3);
    lv_obj_set_width(ui_ContainerL3, 10);
    lv_obj_set_height(ui_ContainerL3, 20);
    lv_obj_set_x(ui_ContainerL3, -30);
    lv_obj_set_y(ui_ContainerL3, 35);
    lv_obj_set_align(ui_ContainerL3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerL3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerL3, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerL3, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerL3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerL3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerL2 = lv_obj_create(ui_Button4);
    lv_obj_remove_style_all(ui_ContainerL2);
    lv_obj_set_width(ui_ContainerL2, 10);
    lv_obj_set_height(ui_ContainerL2, 20);
    lv_obj_set_x(ui_ContainerL2, 0);
    lv_obj_set_y(ui_ContainerL2, 35);
    lv_obj_set_align(ui_ContainerL2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerL2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerL2, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerL2, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerL2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerL2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerL1 = lv_obj_create(ui_Button4);
    lv_obj_remove_style_all(ui_ContainerL1);
    lv_obj_set_width(ui_ContainerL1, 10);
    lv_obj_set_height(ui_ContainerL1, 20);
    lv_obj_set_x(ui_ContainerL1, 30);
    lv_obj_set_y(ui_ContainerL1, 35);
    lv_obj_set_align(ui_ContainerL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerL1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerL1, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerL1, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerL1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerL1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 120);
    lv_obj_set_x(ui_Button6, 172);
    lv_obj_set_y(ui_Button6, 88);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Button6);
    lv_img_set_src(ui_Image6, &ui_img_1371686955);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -17);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 180);

    ui_ContainerR3 = lv_obj_create(ui_Button6);
    lv_obj_remove_style_all(ui_ContainerR3);
    lv_obj_set_width(ui_ContainerR3, 10);
    lv_obj_set_height(ui_ContainerR3, 20);
    lv_obj_set_x(ui_ContainerR3, -30);
    lv_obj_set_y(ui_ContainerR3, 35);
    lv_obj_set_align(ui_ContainerR3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerR3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerR3, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerR3, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerR3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerR3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerR2 = lv_obj_create(ui_Button6);
    lv_obj_remove_style_all(ui_ContainerR2);
    lv_obj_set_width(ui_ContainerR2, 10);
    lv_obj_set_height(ui_ContainerR2, 20);
    lv_obj_set_x(ui_ContainerR2, 0);
    lv_obj_set_y(ui_ContainerR2, 35);
    lv_obj_set_align(ui_ContainerR2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerR2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerR2, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerR2, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerR2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerR2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerR1 = lv_obj_create(ui_Button6);
    lv_obj_remove_style_all(ui_ContainerR1);
    lv_obj_set_width(ui_ContainerR1, 10);
    lv_obj_set_height(ui_ContainerR1, 20);
    lv_obj_set_x(ui_ContainerR1, 30);
    lv_obj_set_y(ui_ContainerR1, 35);
    lv_obj_set_align(ui_ContainerR1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerR1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerR1, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerR1, lv_color_hex(0xFFA100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerR1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerR1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSet = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_ContainerSet);
    lv_obj_set_width(ui_ContainerSet, 212);
    lv_obj_set_height(ui_ContainerSet, 137);
    lv_obj_set_x(ui_ContainerSet, 0);
    lv_obj_set_y(ui_ContainerSet, 86);
    lv_obj_set_align(ui_ContainerSet, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_Panel1, 464);
    lv_obj_set_height(ui_Panel1, 279);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 14);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x00FF03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSet = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonSet, 80);
    lv_obj_set_height(ui_ButtonSet, 60);
    lv_obj_set_x(ui_ButtonSet, 0);
    lv_obj_set_y(ui_ButtonSet, -63);
    lv_obj_set_align(ui_ButtonSet, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_ButtonSet);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SAVE");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSave1 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonSave1, 80);
    lv_obj_set_height(ui_ButtonSave1, 60);
    lv_obj_set_x(ui_ButtonSave1, -1);
    lv_obj_set_y(ui_ButtonSave1, 71);
    lv_obj_set_align(ui_ButtonSave1, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_ButtonSave1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "1");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSet2 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonSet2, 80);
    lv_obj_set_height(ui_ButtonSet2, 60);
    lv_obj_set_x(ui_ButtonSet2, 150);
    lv_obj_set_y(ui_ButtonSet2, -62);
    lv_obj_set_align(ui_ButtonSet2, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_ButtonSet2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "EXIT");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSave2 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonSave2, 80);
    lv_obj_set_height(ui_ButtonSave2, 60);
    lv_obj_set_x(ui_ButtonSave2, 149);
    lv_obj_set_y(ui_ButtonSave2, 73);
    lv_obj_set_align(ui_ButtonSave2, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_ButtonSave2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -164);
    lv_obj_set_y(ui_Label3, 116);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "화면 밝기");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_Panel1);
    lv_slider_set_range(ui_Slider3, 0, 255);
    lv_slider_set_value(ui_Slider3, 255, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 30);
    lv_obj_set_height(ui_Slider3, 210);
    lv_obj_set_x(ui_Slider3, -164);
    lv_obj_set_y(ui_Slider3, -14);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container1, ui_event_Container1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerSet, ui_event_ContainerSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSet, ui_event_ButtonSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSave1, ui_event_ButtonSave1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSet2, ui_event_ButtonSet2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSave2, ui_event_ButtonSave2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);

}
