// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_Marre_SC01-Plus

#include "ui.h"

void ui_ScreenColor_screen_init(void)
{
    ui_ScreenColor = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenColor, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_ScreenColor);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -23);
    lv_obj_set_y(ui_Label29, -140);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "색상 설정");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button32 = lv_btn_create(ui_ScreenColor);
    lv_obj_set_width(ui_Button32, 74);
    lv_obj_set_height(ui_Button32, 46);
    lv_obj_set_x(ui_Button32, 52);
    lv_obj_set_y(ui_Button32, 120);
    lv_obj_set_align(ui_Button32, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button32, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_Button32);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "저장");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_btn_create(ui_ScreenColor);
    lv_obj_set_width(ui_Button16, 68);
    lv_obj_set_height(ui_Button16, 68);
    lv_obj_set_x(ui_Button16, -188);
    lv_obj_set_y(ui_Button16, 10);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button16, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Button16, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x00FFA1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Button16);
    lv_img_set_src(ui_Image2, &ui_img_1965946780);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Button16);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "팝업등");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_ScreenColor);
    lv_obj_set_width(ui_Button17, 68);
    lv_obj_set_height(ui_Button17, 68);
    lv_obj_set_x(ui_Button17, -188);
    lv_obj_set_y(ui_Button17, 100);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Button17, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_Button17);
    lv_img_set_src(ui_Image18, &ui_img_1965946780);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Button17);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "팝업등");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_ScreenColor);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 68);
    lv_obj_set_height(ui_Container5, 68);
    lv_obj_set_x(ui_Container5, -188);
    lv_obj_set_y(ui_Container5, -80);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button33 = lv_btn_create(ui_ScreenColor);
    lv_obj_set_width(ui_Button33, 74);
    lv_obj_set_height(ui_Button33, 46);
    lv_obj_set_x(ui_Button33, 186);
    lv_obj_set_y(ui_Button33, 120);
    lv_obj_set_align(ui_Button33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button33, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Button33);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "취소");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_ScreenColor);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 100);
    lv_obj_set_y(ui_Label33, -80);
    lv_obj_set_align(ui_Label33, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label33, "배경색");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_ScreenColor);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 100);
    lv_obj_set_y(ui_Label34, 10);
    lv_obj_set_align(ui_Label34, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label34, "스위치 켜짐");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_ScreenColor);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 100);
    lv_obj_set_y(ui_Label35, 100);
    lv_obj_set_align(ui_Label35, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label35, "스위치 꺼짐");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_btn_create(ui_ScreenColor);
    lv_obj_set_width(ui_Button31, 74);
    lv_obj_set_height(ui_Button31, 46);
    lv_obj_set_x(ui_Button31, 120);
    lv_obj_set_y(ui_Button31, -132);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Button31);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "초기화");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_ScreenColor);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 200);
    lv_obj_set_height(ui_Container6, 85);
    lv_obj_set_x(ui_Container6, -133);
    lv_obj_set_y(ui_Container6, -80);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_ScreenColor);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 200);
    lv_obj_set_height(ui_Container7, 85);
    lv_obj_set_x(ui_Container7, -133);
    lv_obj_set_y(ui_Container7, 10);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_ScreenColor);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 200);
    lv_obj_set_height(ui_Container8, 85);
    lv_obj_set_x(ui_Container8, -133);
    lv_obj_set_y(ui_Container8, 100);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderRed = lv_slider_create(ui_ScreenColor);
    lv_slider_set_range(ui_SliderRed, 0, 255);
    lv_slider_set_value(ui_SliderRed, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderRed) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderRed, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderRed, 45);
    lv_obj_set_height(ui_SliderRed, 160);
    lv_obj_set_x(ui_SliderRed, 57);
    lv_obj_set_y(ui_SliderRed, -8);
    lv_obj_set_align(ui_SliderRed, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderRed, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderRed, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderRed, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderRed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderRed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderRed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelRed = lv_label_create(ui_SliderRed);
    lv_obj_set_width(ui_LabelRed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRed, "");
    lv_obj_set_style_text_color(ui_LabelRed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderGreen = lv_slider_create(ui_ScreenColor);
    lv_slider_set_range(ui_SliderGreen, 0, 255);
    lv_slider_set_value(ui_SliderGreen, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderGreen) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderGreen, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderGreen, 45);
    lv_obj_set_height(ui_SliderGreen, 160);
    lv_obj_set_x(ui_SliderGreen, 120);
    lv_obj_set_y(ui_SliderGreen, -8);
    lv_obj_set_align(ui_SliderGreen, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderGreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderGreen, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderGreen, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderGreen, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderGreen, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderGreen, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelGreen = lv_label_create(ui_SliderGreen);
    lv_obj_set_width(ui_LabelGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGreen, "");
    lv_obj_set_style_text_color(ui_LabelGreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBlue = lv_slider_create(ui_ScreenColor);
    lv_slider_set_range(ui_SliderBlue, 0, 255);
    lv_slider_set_value(ui_SliderBlue, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBlue) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBlue, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBlue, 45);
    lv_obj_set_height(ui_SliderBlue, 160);
    lv_obj_set_x(ui_SliderBlue, 180);
    lv_obj_set_y(ui_SliderBlue, -8);
    lv_obj_set_align(ui_SliderBlue, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderBlue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBlue, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBlue, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBlue, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBlue, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBlue, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBlue = lv_label_create(ui_SliderBlue);
    lv_obj_set_width(ui_LabelBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBlue, "");
    lv_obj_set_style_text_color(ui_LabelBlue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_ScreenColor);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 200);
    lv_obj_set_height(ui_Container9, 180);
    lv_obj_set_x(ui_Container9, 118);
    lv_obj_set_y(ui_Container9, -8);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button32, ui_event_Button32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button33, ui_event_Button33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container6, ui_event_Container6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container7, ui_event_Container7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container8, ui_event_Container8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderRed, ui_event_SliderRed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderGreen, ui_event_SliderGreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBlue, ui_event_SliderBlue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenColor, ui_event_ScreenColor, LV_EVENT_ALL, NULL);

}
