// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: esp32_ST7789V3

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, -72);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "- 네트워크 읽어오기  -");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 12);
    lv_obj_set_y(ui_Label27, -43);
    lv_obj_set_align(ui_Label27, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label27, "");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_SOYOMapleBold12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConnect = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConnect, 14);
    lv_obj_set_y(ui_LabelConnect, -20);
    lv_obj_set_align(ui_LabelConnect, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelConnect, "");
    lv_obj_set_style_text_font(ui_LabelConnect, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPW = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelPW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPW, 14);
    lv_obj_set_y(ui_LabelPW, 8);
    lv_obj_set_align(ui_LabelPW, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelPW, "");
    lv_obj_set_style_text_font(ui_LabelPW, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button5, 65);
    lv_obj_set_height(ui_Button5, 35);
    lv_obj_set_x(ui_Button5, -105);
    lv_obj_set_y(ui_Button5, 60);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button5, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "연결");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button6, 65);
    lv_obj_set_height(ui_Button6, 35);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 60);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button6, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "읽기");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button7, 65);
    lv_obj_set_height(ui_Button7, 35);
    lv_obj_set_x(ui_Button7, 105);
    lv_obj_set_y(ui_Button7, 60);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button7, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "저장");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

}
