// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_LM_SEAT_8048S050

#include "ui.h"

void ui_ScreenQR_screen_init(void)
{
    ui_ScreenQR = lv_obj_create(NULL);
    lv_obj_add_state(ui_ScreenQR, LV_STATE_PRESSED);       /// States
    lv_obj_clear_flag(ui_ScreenQR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenQR, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -200);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Version :   V1.0");
    lv_obj_add_flag(ui_Label5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFF200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_SOYOMapleBold26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 400);
    lv_obj_set_y(ui_Label23, -81);
    lv_obj_set_align(ui_Label23, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label23, "와이파이 네트워크  :");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSSID = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_LabelSSID, 300);
    lv_obj_set_height(ui_LabelSSID, 40);
    lv_obj_set_x(ui_LabelSSID, 150);
    lv_obj_set_y(ui_LabelSSID, -33);
    lv_obj_set_align(ui_LabelSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSSID, "카인드 V2.0-ST-009");
    lv_obj_set_style_text_align(ui_LabelSSID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSSID, &ui_font_SOYOMapleBold26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelSSID, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelSSID, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelSSID, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPSWD = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_LabelPSWD, 300);
    lv_obj_set_height(ui_LabelPSWD, 40);
    lv_obj_set_x(ui_LabelPSWD, 150);
    lv_obj_set_y(ui_LabelPSWD, 89);
    lv_obj_set_align(ui_LabelPSWD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPSWD, "17241126009");
    lv_obj_set_style_text_align(ui_LabelPSWD, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPSWD, &ui_font_SOYOMapleBold26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPSWD, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPSWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPSWD, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPSWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPSWD, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 400);
    lv_obj_set_y(ui_Label24, 43);
    lv_obj_set_align(ui_Label24, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label24, "와이파이 비밀번호  :");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageQR = lv_img_create(ui_ScreenQR);
    lv_img_set_src(ui_ImageQR, &ui_img_1187412780);
    lv_obj_set_width(ui_ImageQR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageQR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageQR, -200);
    lv_obj_set_y(ui_ImageQR, -40);
    lv_obj_set_align(ui_ImageQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageQR, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_outline_color(ui_ImageQR, lv_color_hex(0x00FF21), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ImageQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ImageQR, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ImageQR, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_ScreenQR);
    lv_slider_set_range(ui_Slider2, 10, 255);
    lv_slider_set_value(ui_Slider2, 127, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 280);
    lv_obj_set_height(ui_Slider2, 5);
    lv_obj_set_x(ui_Slider2, -200);
    lv_obj_set_y(ui_Slider2, 186);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Slider2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Slider2, 15, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 600);
    lv_obj_set_y(ui_Label37, -170);
    lv_obj_set_align(ui_Label37, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label37, "마스타");
    lv_obj_set_style_text_align(ui_Label37, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -302);
    lv_obj_set_y(ui_Label39, -170);
    lv_obj_set_align(ui_Label39, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label39, "슬레이브");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ScreenQR);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 800);
    lv_obj_set_height(ui_Container2, 380);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -49);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Switch1 = lv_switch_create(ui_ScreenQR);
    lv_obj_set_width(ui_Switch1, 60);
    lv_obj_set_height(ui_Switch1, 30);
    lv_obj_set_x(ui_Switch1, 150);
    lv_obj_set_y(ui_Switch1, -170);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States


    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container2, ui_event_Container2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);

}
