// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SQL-ST7735-V1.0

#include "ui.h"

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 158);
    lv_obj_set_height(ui_Container3, 80);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 150);
    lv_obj_set_height(ui_Container1, 25);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -18);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x3BFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSSID = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSSID, "카인드 V3.0-CD-081");
    lv_obj_set_style_text_color(ui_LabelSSID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSSID, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 150);
    lv_obj_set_height(ui_Container2, 26);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 18);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x3BFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPSWD = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LabelPSWD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPSWD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPSWD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPSWD, "13250302081");
    lv_obj_set_style_text_color(ui_LabelPSWD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPSWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPSWD, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);

}
