// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SQL-ST7735-V1.0

#include "ui.h"

void ui_ScreenText_screen_init(void)
{
    ui_ScreenText = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenText, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_ScreenText);
    lv_obj_set_width(ui_TextArea1, 160);
    lv_obj_set_height(ui_TextArea1, 80);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TextArea1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SOYOMapleBold12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_ScreenText);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 41);
    lv_obj_set_height(ui_Container4, 80);
    lv_obj_set_x(ui_Container4, 57);
    lv_obj_set_y(ui_Container4, 0);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x000DFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCount = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCount, 0);
    lv_obj_set_y(ui_LabelCount, -27);
    lv_obj_set_align(ui_LabelCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCount, "0");
    lv_obj_set_style_text_font(ui_LabelCount, &ui_font_SOYOMapleBold12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageNetWork = lv_img_create(ui_Container4);
    lv_img_set_src(ui_ImageNetWork, &ui_img_network_png);
    lv_obj_set_width(ui_ImageNetWork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageNetWork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageNetWork, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNetWork, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageNetWork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageNetWork, 120);

    ui_ImageWiFi = lv_img_create(ui_Container4);
    lv_img_set_src(ui_ImageWiFi, &ui_img_wifi_png);
    lv_obj_set_width(ui_ImageWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWiFi, 0);
    lv_obj_set_y(ui_ImageWiFi, 26);
    lv_obj_set_align(ui_ImageWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWiFi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageWiFi, 120);

}
