// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-CarInd-SC01-PLUS-V2.0

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ScreenHomeLoaded(lv_event_t * e);
void logoDisplay(lv_event_t * e);
void pwmChangeSlider(lv_event_t * e);
void led1Long(lv_event_t * e);
void ledButton1(lv_event_t * e);
void led2Long(lv_event_t * e);
void ledButton2(lv_event_t * e);
void led3Long(lv_event_t * e);
void ledButton3(lv_event_t * e);
void ledButton4(lv_event_t * e);
void led4Long(lv_event_t * e);
void pumpButton(lv_event_t * e);
void cigarButton(lv_event_t * e);
void frigeButton(lv_event_t * e);
void tvButton(lv_event_t * e);
void invertorButton(lv_event_t * e);
void brightChangeSlider(lv_event_t * e);
void sleepButton(lv_event_t * e);
void timeClick(lv_event_t * e);
void sleepOff(lv_event_t * e);
void nameInitClick(lv_event_t * e);
void brightQR(lv_event_t * e);
void masterModeSelect(lv_event_t * e);
void logoClick(lv_event_t * e);
void timeChanged(lv_event_t * e);
void nowTimeSave(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
