// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-CarInd-SC01-PLUS-V2.0

#include "ui.h"

void ui_ScreenClock_screen_init(void)
{
    ui_ScreenClock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenClock, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_ScreenClock);
    lv_img_set_src(ui_Image13, &ui_img_638533140);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, -206);
    lv_obj_set_y(ui_Image13, -130);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -118);
    lv_obj_set_y(ui_Label10, -130);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "현재 시간 설정");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNowTime = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_LabelNowTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNowTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNowTime, -36);
    lv_obj_set_y(ui_LabelNowTime, -130);
    lv_obj_set_align(ui_LabelNowTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelNowTime, "20년 12월 30일 16시 30분");
    lv_obj_set_style_text_color(ui_LabelNowTime, lv_color_hex(0xEDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNowTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNowTime, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerYear = lv_roller_create(ui_ScreenClock);
    lv_roller_set_options(ui_RollerYear,
                          "2024\n2025\n2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n2034\n2035\n2036\n2037\n2038\n2039\n2040\n2041\n2042\n2043\n2044\n2045\n2046\n2047\n2048\n2049\n2050\n2051\n2052\n2053\n2054",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerYear, 80);
    lv_obj_set_height(ui_RollerYear, 160);
    lv_obj_set_x(ui_RollerYear, -191);
    lv_obj_set_y(ui_RollerYear, -10);
    lv_obj_set_align(ui_RollerYear, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerYear, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerYear, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerYear, lv_color_hex(0xFFF700), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerYear, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerYear, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -138);
    lv_obj_set_y(ui_Label11, -10);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "년");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xEDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerMonth = lv_roller_create(ui_ScreenClock);
    lv_roller_set_options(ui_RollerMonth, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerMonth, 50);
    lv_obj_set_height(ui_RollerMonth, 160);
    lv_obj_set_x(ui_RollerMonth, -95);
    lv_obj_set_y(ui_RollerMonth, -10);
    lv_obj_set_align(ui_RollerMonth, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerMonth, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerMonth, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerMonth, lv_color_hex(0xFFF700), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerMonth, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerMonth, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -59);
    lv_obj_set_y(ui_Label12, -10);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "월");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xEDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerDay = lv_roller_create(ui_ScreenClock);
    lv_roller_set_options(ui_RollerDay,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerDay, 50);
    lv_obj_set_height(ui_RollerDay, 160);
    lv_obj_set_x(ui_RollerDay, -11);
    lv_obj_set_y(ui_RollerDay, -10);
    lv_obj_set_align(ui_RollerDay, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerDay, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerDay, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerDay, lv_color_hex(0xFFF700), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerDay, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerDay, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 26);
    lv_obj_set_y(ui_Label13, -10);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "일");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xEDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerHour = lv_roller_create(ui_ScreenClock);
    lv_roller_set_options(ui_RollerHour,
                          "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerHour, 50);
    lv_obj_set_height(ui_RollerHour, 160);
    lv_obj_set_x(ui_RollerHour, 95);
    lv_obj_set_y(ui_RollerHour, -10);
    lv_obj_set_align(ui_RollerHour, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerHour, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerHour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerHour, lv_color_hex(0xFFF700), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerHour, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 131);
    lv_obj_set_y(ui_Label14, -10);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "시");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xEDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerMin = lv_roller_create(ui_ScreenClock);
    lv_roller_set_options(ui_RollerMin,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerMin, 50);
    lv_obj_set_height(ui_RollerMin, 160);
    lv_obj_set_x(ui_RollerMin, 183);
    lv_obj_set_y(ui_RollerMin, -10);
    lv_obj_set_align(ui_RollerMin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerMin, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerMin, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerMin, lv_color_hex(0xFFF700), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerMin, &lv_font_montserrat_22, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ScreenClock);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 219);
    lv_obj_set_y(ui_Label15, -10);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "분");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xEDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_ScreenClock);
    lv_obj_set_width(ui_Button10, 80);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 60);
    lv_obj_set_y(ui_Button10, 120);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "저장");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_ScreenClock);
    lv_obj_set_width(ui_Button11, 80);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, 174);
    lv_obj_set_y(ui_Button11, 120);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);

    ui_Label17 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "종료");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RollerYear, ui_event_RollerYear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerMonth, ui_event_RollerMonth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerDay, ui_event_RollerDay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerHour, ui_event_RollerHour, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerMin, ui_event_RollerMin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
