// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: esp32_ST7789V3_Touch

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);

    ui_Panel4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel4, 278);
    lv_obj_set_height(ui_Panel4, 350);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 56);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel4, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_radius(ui_Panel4, 46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 0);
    lv_obj_set_y(ui_Label30, -150);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "전원 공급 시 자동 켜짐 기능 ");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 120);
    lv_obj_set_height(ui_Container1, 30);
    lv_obj_set_x(ui_Container1, -65);
    lv_obj_set_y(ui_Container1, 40);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledSwitch1 = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_ledSwitch1, 50);
    lv_obj_set_height(ui_ledSwitch1, 25);
    lv_obj_set_x(ui_ledSwitch1, 20);
    lv_obj_set_y(ui_ledSwitch1, 0);
    lv_obj_set_align(ui_ledSwitch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ledSwitch1, LV_STATE_CHECKED);       /// States


    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -40);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "LED 1");

    ui_Container2 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 120);
    lv_obj_set_height(ui_Container2, 30);
    lv_obj_set_x(ui_Container2, -65);
    lv_obj_set_y(ui_Container2, 80);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledSwitch2 = lv_switch_create(ui_Container2);
    lv_obj_set_width(ui_ledSwitch2, 50);
    lv_obj_set_height(ui_ledSwitch2, 25);
    lv_obj_set_x(ui_ledSwitch2, 20);
    lv_obj_set_y(ui_ledSwitch2, 0);
    lv_obj_set_align(ui_ledSwitch2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ledSwitch2, LV_STATE_CHECKED);       /// States


    ui_Label2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -40);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "LED 2");

    ui_Container3 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 120);
    lv_obj_set_height(ui_Container3, 30);
    lv_obj_set_x(ui_Container3, -65);
    lv_obj_set_y(ui_Container3, 120);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledSwitch3 = lv_switch_create(ui_Container3);
    lv_obj_set_width(ui_ledSwitch3, 50);
    lv_obj_set_height(ui_ledSwitch3, 25);
    lv_obj_set_x(ui_ledSwitch3, 20);
    lv_obj_set_y(ui_ledSwitch3, 0);
    lv_obj_set_align(ui_ledSwitch3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ledSwitch3, LV_STATE_CHECKED);       /// States


    ui_Label19 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -40);
    lv_obj_set_y(ui_Label19, 0);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "LED 3");

    ui_Container4 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 120);
    lv_obj_set_height(ui_Container4, 30);
    lv_obj_set_x(ui_Container4, -65);
    lv_obj_set_y(ui_Container4, 160);
    lv_obj_set_align(ui_Container4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledSwitch4 = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_ledSwitch4, 50);
    lv_obj_set_height(ui_ledSwitch4, 25);
    lv_obj_set_x(ui_ledSwitch4, 20);
    lv_obj_set_y(ui_ledSwitch4, 0);
    lv_obj_set_align(ui_ledSwitch4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ledSwitch4, LV_STATE_CHECKED);       /// States


    ui_Label20 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -40);
    lv_obj_set_y(ui_Label20, 0);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "LED 4");

    ui_Container5 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 120);
    lv_obj_set_height(ui_Container5, 30);
    lv_obj_set_x(ui_Container5, -65);
    lv_obj_set_y(ui_Container5, 200);
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledSwitch5 = lv_switch_create(ui_Container5);
    lv_obj_set_width(ui_ledSwitch5, 50);
    lv_obj_set_height(ui_ledSwitch5, 25);
    lv_obj_set_x(ui_ledSwitch5, 20);
    lv_obj_set_y(ui_ledSwitch5, 0);
    lv_obj_set_align(ui_ledSwitch5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ledSwitch5, LV_STATE_CHECKED);       /// States


    ui_Label21 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -40);
    lv_obj_set_y(ui_Label21, 0);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "LED 5");

    ui_Container6 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 120);
    lv_obj_set_height(ui_Container6, 30);
    lv_obj_set_x(ui_Container6, -65);
    lv_obj_set_y(ui_Container6, 240);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledSwitch6 = lv_switch_create(ui_Container6);
    lv_obj_set_width(ui_ledSwitch6, 50);
    lv_obj_set_height(ui_ledSwitch6, 25);
    lv_obj_set_x(ui_ledSwitch6, 20);
    lv_obj_set_y(ui_ledSwitch6, 0);
    lv_obj_set_align(ui_ledSwitch6, LV_ALIGN_CENTER);


    ui_Label23 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -40);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "LED 6");

    ui_Container7 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 120);
    lv_obj_set_height(ui_Container7, 30);
    lv_obj_set_x(ui_Container7, 65);
    lv_obj_set_y(ui_Container7, 40);
    lv_obj_set_align(ui_Container7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outSwitch1 = lv_switch_create(ui_Container7);
    lv_obj_set_width(ui_outSwitch1, 50);
    lv_obj_set_height(ui_outSwitch1, 25);
    lv_obj_set_x(ui_outSwitch1, 27);
    lv_obj_set_y(ui_outSwitch1, 0);
    lv_obj_set_align(ui_outSwitch1, LV_ALIGN_CENTER);


    ui_Label24 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -30);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "OUT 1");

    ui_Container8 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 120);
    lv_obj_set_height(ui_Container8, 30);
    lv_obj_set_x(ui_Container8, 65);
    lv_obj_set_y(ui_Container8, 80);
    lv_obj_set_align(ui_Container8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outSwitch2 = lv_switch_create(ui_Container8);
    lv_obj_set_width(ui_outSwitch2, 50);
    lv_obj_set_height(ui_outSwitch2, 25);
    lv_obj_set_x(ui_outSwitch2, 27);
    lv_obj_set_y(ui_outSwitch2, 0);
    lv_obj_set_align(ui_outSwitch2, LV_ALIGN_CENTER);


    ui_Label25 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -30);
    lv_obj_set_y(ui_Label25, 0);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "OUT 2");

    ui_Container9 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 120);
    lv_obj_set_height(ui_Container9, 30);
    lv_obj_set_x(ui_Container9, 65);
    lv_obj_set_y(ui_Container9, 120);
    lv_obj_set_align(ui_Container9, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outSwitch3 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_outSwitch3, 50);
    lv_obj_set_height(ui_outSwitch3, 25);
    lv_obj_set_x(ui_outSwitch3, 27);
    lv_obj_set_y(ui_outSwitch3, 0);
    lv_obj_set_align(ui_outSwitch3, LV_ALIGN_CENTER);


    ui_Label26 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -30);
    lv_obj_set_y(ui_Label26, 0);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "OUT 3");

    ui_Container10 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 120);
    lv_obj_set_height(ui_Container10, 30);
    lv_obj_set_x(ui_Container10, 65);
    lv_obj_set_y(ui_Container10, 160);
    lv_obj_set_align(ui_Container10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outSwitch4 = lv_switch_create(ui_Container10);
    lv_obj_set_width(ui_outSwitch4, 50);
    lv_obj_set_height(ui_outSwitch4, 25);
    lv_obj_set_x(ui_outSwitch4, 27);
    lv_obj_set_y(ui_outSwitch4, 0);
    lv_obj_set_align(ui_outSwitch4, LV_ALIGN_CENTER);


    ui_Label27 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -30);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "OUT 4");

    ui_Container11 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 120);
    lv_obj_set_height(ui_Container11, 30);
    lv_obj_set_x(ui_Container11, 65);
    lv_obj_set_y(ui_Container11, 200);
    lv_obj_set_align(ui_Container11, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outSwitch5 = lv_switch_create(ui_Container11);
    lv_obj_set_width(ui_outSwitch5, 50);
    lv_obj_set_height(ui_outSwitch5, 25);
    lv_obj_set_x(ui_outSwitch5, 27);
    lv_obj_set_y(ui_outSwitch5, 0);
    lv_obj_set_align(ui_outSwitch5, LV_ALIGN_CENTER);


    ui_Label28 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -30);
    lv_obj_set_y(ui_Label28, 0);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "OUT 5");

    ui_Container12 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 120);
    lv_obj_set_height(ui_Container12, 30);
    lv_obj_set_x(ui_Container12, 65);
    lv_obj_set_y(ui_Container12, 240);
    lv_obj_set_align(ui_Container12, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outSwitch6 = lv_switch_create(ui_Container12);
    lv_obj_set_width(ui_outSwitch6, 50);
    lv_obj_set_height(ui_outSwitch6, 25);
    lv_obj_set_x(ui_outSwitch6, 27);
    lv_obj_set_y(ui_outSwitch6, 0);
    lv_obj_set_align(ui_outSwitch6, LV_ALIGN_CENTER);


    ui_Label29 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -30);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "OUT 6");

    ui_Button4 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Button4, 80);
    lv_obj_set_height(ui_Button4, 40);
    lv_obj_set_x(ui_Button4, -60);
    lv_obj_set_y(ui_Button4, 145);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xF90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "저장 ");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Panel4);
    lv_obj_set_width(ui_Button6, 80);
    lv_obj_set_height(ui_Button6, 40);
    lv_obj_set_x(ui_Button6, 60);
    lv_obj_set_y(ui_Button6, 145);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "취소");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
