// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SQL_LM_LED_8048S050-V3.0

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
lv_obj_t * ui_ScreenHome;
void ui_event_Container1(lv_event_t * e);
lv_obj_t * ui_Container1;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;
lv_obj_t * ui_ImageSwitch;
lv_obj_t * ui_ImageDoor;
lv_obj_t * ui_ImageBattery;
lv_obj_t * ui_ImageNetwork;
void ui_event_ContainerSetting(lv_event_t * e);
lv_obj_t * ui_ContainerSetting;
lv_obj_t * ui_ImageSetting;
lv_obj_t * ui_Label7;
void ui_event_ContainerWiFi(lv_event_t * e);
lv_obj_t * ui_ContainerWiFi;
lv_obj_t * ui_ImageWiFi;
lv_obj_t * ui_LabelBright;
lv_obj_t * ui_LabelBGBright;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
lv_obj_t * ui_LabelLED;
lv_obj_t * ui_LabelBr;
lv_obj_t * ui_PanelButton;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label1;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label4;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label2;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label5;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label3;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Container12;
void ui_event_PanelMessage(lv_event_t * e);
lv_obj_t * ui_PanelMessage;
lv_obj_t * ui_LabelMessage;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label10;
lv_obj_t * ui_ContainerMasking;
lv_obj_t * ui_Container16;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenQR
void ui_ScreenQR_screen_init(void);
lv_obj_t * ui_ScreenQR;
lv_obj_t * ui_Label23;
lv_obj_t * ui_LabelSSID;
lv_obj_t * ui_LabelPSWD;
lv_obj_t * ui_Label24;
lv_obj_t * ui_ImageQR;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label39;
void ui_event_Container2(lv_event_t * e);
lv_obj_t * ui_Container2;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenUserSet
void ui_ScreenUserSet_screen_init(void);
void ui_event_ScreenUserSet(lv_event_t * e);
lv_obj_t * ui_ScreenUserSet;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label18;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label19;
void ui_event_Roller1(lv_event_t * e);
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Container6;
void ui_event_SliderRed(lv_event_t * e);
lv_obj_t * ui_SliderRed;
void ui_event_SliderGreen(lv_event_t * e);
lv_obj_t * ui_SliderGreen;
void ui_event_SliderBlue(lv_event_t * e);
lv_obj_t * ui_SliderBlue;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label50;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label11;
void ui_event_Button24(lv_event_t * e);
lv_obj_t * ui_Button24;
lv_obj_t * ui_Label12;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
lv_obj_t * ui_Label14;
void ui_event_Button26(lv_event_t * e);
lv_obj_t * ui_Button26;
lv_obj_t * ui_Label28;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
void ui_event_ScreenSetting(lv_event_t * e);
lv_obj_t * ui_ScreenSetting;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label15;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
void ui_event_SwitchMood(lv_event_t * e);
lv_obj_t * ui_SwitchMood;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label45;
void ui_event_SwitchSide(lv_event_t * e);
lv_obj_t * ui_SwitchSide;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenLogo
void ui_ScreenLogo_screen_init(void);
void ui_event_ScreenLogo(lv_event_t * e);
lv_obj_t * ui_ScreenLogo;
lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenLogo2
void ui_ScreenLogo2_screen_init(void);
void ui_event_ScreenLogo2(lv_event_t * e);
lv_obj_t * ui_ScreenLogo2;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenHomeLoaded(e);
    }
}

void ui_event_Container1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        logoChangeClick(e);
    }
}

void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        logoClick(e);
    }
}

void ui_event_ContainerSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        settingClick(e);
        _ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSetting_screen_init);
    }
}

void ui_event_ContainerWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        wifiClick(e);
        _ui_screen_change(&ui_ScreenQR, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenQR_screen_init);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBright, target, "", "");
        pwmChangeSlider(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        setLEDPwm(e);
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        BGBright(e);
        _ui_slider_set_text_value(ui_LabelBGBright, target, "", "");
    }
    if(event_code == LV_EVENT_RELEASED) {
        setBright(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        led1Left(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton1(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton4(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        led4Left(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        led2Left(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton2(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        led2GestureRight(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button5, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton5(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        led5Left(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        led3Left(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton3(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        led3GestureRight(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button6, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        tvButton(e);
    }
}

void ui_event_PanelMessage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        panelMessageClick(e);
        _ui_flag_modify(ui_PanelMessage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button11, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        tvOutButton(e);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brightQR(e);
    }
}

void ui_event_Container2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        masterModeSelect(e);
    }
}

void ui_event_ScreenUserSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenUserSetLoad(e);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
        userSetting(e);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
        userSettingCancel(e);
    }
}

void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rollerNeoMode(e);
    }
}

void ui_event_SliderRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SliderRed(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        SliderRedReleased(e);
    }
}

void ui_event_SliderGreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SliderGreen(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        SliderGreenReleased(e);
    }
}

void ui_event_SliderBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SliderBlue(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        SliderBlueReleased(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        neoMode1(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        neoMode2(e);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        neoMode3(e);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        neoMode4(e);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        neoMode5(e);
    }
}

void ui_event_ScreenSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenSettingLoad(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
        factorySetting(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
        factorySettingCancel(e);
    }
}

void ui_event_SwitchMood(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        switchMood(e);
    }
}

void ui_event_SwitchSide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        switchSide(e);
    }
}

void ui_event_ScreenLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
        logoFlagReset(e);
    }
}

void ui_event_ScreenLogo2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
        logoFlagReset(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenHome_screen_init();
    ui_ScreenQR_screen_init();
    ui_ScreenUserSet_screen_init();
    ui_ScreenSetting_screen_init();
    ui_ScreenLogo_screen_init();
    ui_ScreenLogo2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenHome);
}
