// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-ST7789-MotorHome

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void screen1Loaded(lv_event_t * e);
void panelVolt(lv_event_t * e);
void voltPlus(lv_event_t * e);
void voltMinus(lv_event_t * e);
void voltSave(lv_event_t * e);
void factoryProccess(lv_event_t * e);
void opacityChange(lv_event_t * e);
void sensorValueSet(lv_event_t * e);
void screen4Loaded(lv_event_t * e);
void btnSensorSelectSave(lv_event_t * e);
void screen5Loaded(lv_event_t * e);
void SensorLowSave(lv_event_t * e);
void SensorHighSave(lv_event_t * e);
void btnSensorValueSave(lv_event_t * e);
void sensorValueSelect(lv_event_t * e);
void screen6Loaded(lv_event_t * e);
void btnPowerOnExeSave(lv_event_t * e);
void networkScreenLoaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
