// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-ST7789-MotorHome

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);

    ui_QRImage = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_QRImage, &ui_img_1296478115);
    lv_obj_set_width(ui_QRImage, 150);
    lv_obj_set_height(ui_QRImage, 150);
    lv_obj_set_x(ui_QRImage, -20);
    lv_obj_set_y(ui_QRImage, 29);
    lv_obj_set_align(ui_QRImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QRImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_QRImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SSIDLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDLabel, -20);
    lv_obj_set_y(ui_SSIDLabel, -100);
    lv_obj_set_align(ui_SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLabel, "CamTrol V5.0-T-086");
    lv_obj_set_style_text_font(ui_SSIDLabel, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_PWLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWLabel, -20);
    lv_obj_set_y(ui_PWLabel, -70);
    lv_obj_set_align(ui_PWLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWLabel, "03240701086");
    lv_obj_add_flag(ui_PWLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_PWLabel, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_Screen2);
    lv_roller_set_options(ui_Roller2, "100\n95\n90\n85\n80\n75\n70\n65\n60\n55\n50\n45\n40\n35\n30\n25\n20\n15\n10\n5",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 150);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, 98);
    lv_obj_set_y(ui_Roller2, 29);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Roller2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMsg = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMsg, -19);
    lv_obj_set_y(ui_LabelMsg, 24);
    lv_obj_set_align(ui_LabelMsg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMsg, "위의 네트워크 아이디로\n접속합니다.");
    lv_obj_add_flag(ui_LabelMsg, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelMsg, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_QRImage, ui_event_QRImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PWLabel, ui_event_PWLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller2, ui_event_Roller2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
