// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-ST7789-MotorHome

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 280);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Panel1, 46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_TextArea1, 238);
    lv_obj_set_height(ui_TextArea1, 155);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 28);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TextArea1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_TextArea1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_TextArea1, LV_DIR_VER);
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextArea1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextArea1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelVolt = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVolt, 20);
    lv_obj_set_y(ui_LabelVolt, -100);
    lv_obj_set_align(ui_LabelVolt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelVolt, "전압: 10.0V");
    lv_obj_set_style_text_font(ui_LabelVolt, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelVolt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelVolt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelVolt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelVolt, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFuel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelFuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFuel, 135);
    lv_obj_set_y(ui_LabelFuel, -100);
    lv_obj_set_align(ui_LabelFuel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelFuel, "연료: 100%");
    lv_obj_set_style_text_font(ui_LabelFuel, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelFuel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelFuel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelFuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelFuel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelFuel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClean = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelClean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelClean, 20);
    lv_obj_set_y(ui_LabelClean, -68);
    lv_obj_set_align(ui_LabelClean, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelClean, "청수: 100%");
    lv_obj_set_style_text_font(ui_LabelClean, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelClean, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelClean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelClean, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelClean, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWaste = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelWaste, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWaste, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWaste, 135);
    lv_obj_set_y(ui_LabelWaste, -68);
    lv_obj_set_align(ui_LabelWaste, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWaste, "오수: 100%");
    lv_obj_set_style_text_font(ui_LabelWaste, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelWaste, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelWaste, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelWaste, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelWaste, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelWaste, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVolt = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelVolt, 226);
    lv_obj_set_height(ui_PanelVolt, 144);
    lv_obj_set_x(ui_PanelVolt, 0);
    lv_obj_set_y(ui_PanelVolt, 28);
    lv_obj_set_align(ui_PanelVolt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelVolt, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelVolt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelV1 = lv_label_create(ui_PanelVolt);
    lv_obj_set_width(ui_labelV1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelV1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelV1, -52);
    lv_obj_set_y(ui_labelV1, -40);
    lv_obj_set_align(ui_labelV1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelV1, "밧데리 전압\n오프셋 조정");
    lv_obj_set_style_text_font(ui_labelV1, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volt = lv_label_create(ui_PanelVolt);
    lv_obj_set_width(ui_volt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volt, -135);
    lv_obj_set_y(ui_volt, 8);
    lv_obj_set_align(ui_volt, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_volt, "0.00");
    lv_obj_set_style_text_font(ui_volt, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelV = lv_label_create(ui_PanelVolt);
    lv_obj_set_width(ui_labelV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelV, -18);
    lv_obj_set_y(ui_labelV, 8);
    lv_obj_set_align(ui_labelV, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelV, "V");
    lv_obj_set_style_text_font(ui_labelV, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_PanelVolt);
    lv_obj_set_width(ui_Button3, 60);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 64);
    lv_obj_set_y(ui_Button3, -50);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelPlus = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_labelPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPlus, 4);
    lv_obj_set_y(ui_labelPlus, -1);
    lv_obj_set_align(ui_labelPlus, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_labelPlus, "+");
    lv_obj_set_style_text_font(ui_labelPlus, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_PanelVolt);
    lv_obj_set_width(ui_Button5, 60);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 65);
    lv_obj_set_y(ui_Button5, 0);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelMinus = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_labelMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMinus, 4);
    lv_obj_set_y(ui_labelMinus, -1);
    lv_obj_set_align(ui_labelMinus, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_labelMinus, "-");
    lv_obj_set_style_text_font(ui_labelMinus, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_PanelVolt);
    lv_obj_set_width(ui_Button8, 60);
    lv_obj_set_height(ui_Button8, 40);
    lv_obj_set_x(ui_Button8, 64);
    lv_obj_set_y(ui_Button8, 50);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_state(ui_Button8, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelMinus1 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_labelMinus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMinus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelMinus1, 4);
    lv_obj_set_y(ui_labelMinus1, -1);
    lv_obj_set_align(ui_labelMinus1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_labelMinus1, "저장");
    lv_obj_set_style_text_font(ui_labelMinus1, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_logo_png);
    lv_obj_set_width(ui_Image1, 280);
    lv_obj_set_height(ui_Image1, 240);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Image1, LV_STATE_DISABLED);       /// States
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Image1, LV_SCROLLBAR_MODE_OFF);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
