// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-ST7789-MotorHome

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);

    ui_Panel3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel3, 278);
    lv_obj_set_height(ui_Panel3, 300);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 32);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, -128);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "센서 값 설정");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 259);
    lv_obj_set_height(ui_Container13, 130);
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, 6);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -90);
    lv_obj_set_y(ui_Label16, -40);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "하한 값");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 90);
    lv_obj_set_y(ui_Label18, -40);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "상한 값");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorLowValue = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_sensorLowValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorLowValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorLowValue, -90);
    lv_obj_set_y(ui_sensorLowValue, -10);
    lv_obj_set_align(ui_sensorLowValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorLowValue, "0");
    lv_obj_set_style_text_color(ui_sensorLowValue, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensorLowValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensorLowValue, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorHighValue = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_sensorHighValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorHighValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorHighValue, 90);
    lv_obj_set_y(ui_sensorHighValue, -10);
    lv_obj_set_align(ui_sensorHighValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorHighValue, "0");
    lv_obj_set_style_text_color(ui_sensorHighValue, lv_color_hex(0xFCFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensorHighValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensorHighValue, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -40);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "현재 값");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorNowValue = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_sensorNowValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorNowValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorNowValue, 0);
    lv_obj_set_y(ui_sensorNowValue, -10);
    lv_obj_set_align(ui_sensorNowValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorNowValue, "12345");
    lv_obj_set_style_text_color(ui_sensorNowValue, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensorNowValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensorNowValue, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorLowSave = lv_btn_create(ui_Container13);
    lv_obj_set_width(ui_sensorLowSave, 60);
    lv_obj_set_height(ui_sensorLowSave, 40);
    lv_obj_set_x(ui_sensorLowSave, -90);
    lv_obj_set_y(ui_sensorLowSave, 34);
    lv_obj_set_align(ui_sensorLowSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sensorLowSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sensorLowSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sensorHighSave = lv_btn_create(ui_Container13);
    lv_obj_set_width(ui_sensorHighSave, 60);
    lv_obj_set_height(ui_sensorHighSave, 40);
    lv_obj_set_x(ui_sensorHighSave, 90);
    lv_obj_set_y(ui_sensorHighSave, 34);
    lv_obj_set_align(ui_sensorHighSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sensorHighSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sensorHighSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnSenValue = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_BtnSenValue, 80);
    lv_obj_set_height(ui_BtnSenValue, 40);
    lv_obj_set_x(ui_BtnSenValue, -55);
    lv_obj_set_y(ui_BtnSenValue, 115);
    lv_obj_set_align(ui_BtnSenValue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSenValue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSenValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSenValue, lv_color_hex(0xF90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSenValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_BtnSenValue);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "저장");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button7, 80);
    lv_obj_set_height(ui_Button7, 40);
    lv_obj_set_x(ui_Button7, 55);
    lv_obj_set_y(ui_Button7, 115);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label46 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "취소");
    lv_obj_set_style_text_font(ui_Label46, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchSensorType = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_switchSensorType, 60);
    lv_obj_set_height(ui_switchSensorType, 35);
    lv_obj_set_x(ui_switchSensorType, 2);
    lv_obj_set_y(ui_switchSensorType, -90);
    lv_obj_set_align(ui_switchSensorType, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_switchSensorType, LV_STATE_CHECKED);       /// States


    ui_Label1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -78);
    lv_obj_set_y(ui_Label1, -90);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "240~33");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 79);
    lv_obj_set_y(ui_Label6, -90);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "0~190");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_sensorLowSave, ui_event_sensorLowSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sensorHighSave, ui_event_sensorHighSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSenValue, ui_event_BtnSenValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchSensorType, ui_event_switchSensorType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
