// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_AuToHomes_SC01

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void sec_Animation(lv_obj_t * TargetObject, int delay);
void secDot_Animation(lv_obj_t * TargetObject, int delay);
void PanelButton_Animation(lv_obj_t * TargetObject, int delay);
void PanelDisplay_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
lv_obj_t * ui_ScreenHome;
lv_obj_t * ui_Container1;
lv_obj_t * ui_ImageWiFi;
lv_obj_t * ui_ImageHotSpot;
lv_obj_t * ui_LabelDay;
lv_obj_t * ui_LabelAmPm;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_LabelSec;
lv_obj_t * ui_LabelMin;
lv_obj_t * ui_Image1;
lv_obj_t * ui_ImageSleepOff;
lv_obj_t * ui_ImageSleepOn;
void ui_event_Container4(lv_event_t * e);
lv_obj_t * ui_Container4;
lv_obj_t * ui_PanelDisplay;
lv_obj_t * ui_Image3;
lv_obj_t * ui_LabelVolt;
lv_obj_t * ui_ImageTemp;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_ImageHumi;
lv_obj_t * ui_LabelHumi;
void ui_event_Image20(lv_event_t * e);
lv_obj_t * ui_Image20;
lv_obj_t * ui_LabelBright;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_LabelLED;
lv_obj_t * ui_PanelButton;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label9;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label20;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label21;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label22;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
void ui_event_PanelMessage(lv_event_t * e);
lv_obj_t * ui_PanelMessage;
lv_obj_t * ui_LabelSecCount;
lv_obj_t * ui_LabelMessage;
void ui_event_ContainerWiFi(lv_event_t * e);
lv_obj_t * ui_ContainerWiFi;
void ui_event_ContainerLock(lv_event_t * e);
lv_obj_t * ui_ContainerLock;
lv_obj_t * ui_ImageLock;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenQR
void ui_ScreenQR_screen_init(void);
lv_obj_t * ui_ScreenQR;
lv_obj_t * ui_Label23;
lv_obj_t * ui_LabelSSID;
lv_obj_t * ui_LabelPSWD;
lv_obj_t * ui_Label24;
lv_obj_t * ui_ImageQR;
lv_obj_t * ui_SpinnerHotSpot;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
void ui_event_Container2(lv_event_t * e);
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label40;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_SwitchNetwork(lv_event_t * e);
lv_obj_t * ui_SwitchNetwork;
void ui_event_Label41(lv_event_t * e);
lv_obj_t * ui_Label41;
lv_obj_t * ui_PanelNetwork;
void ui_event_TextAreaSSID(lv_event_t * e);
lv_obj_t * ui_TextAreaSSID;
void ui_event_TextAreaPSWD(lv_event_t * e);
lv_obj_t * ui_TextAreaPSWD;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label44;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label45;
void ui_event_RollerHotSpot(lv_event_t * e);
lv_obj_t * ui_RollerHotSpot;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSleep
void ui_ScreenSleep_screen_init(void);
void ui_event_ScreenSleep(lv_event_t * e);
lv_obj_t * ui_ScreenSleep;
lv_obj_t * ui_Label10;
void ui_event_Roller4(lv_event_t * e);
lv_obj_t * ui_Roller4;
lv_obj_t * ui_Label14;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label18;
void ui_event_Button22(lv_event_t * e);
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label19;
void ui_event_Roller1(lv_event_t * e);
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenColor
void ui_ScreenColor_screen_init(void);
void ui_event_ScreenColor(lv_event_t * e);
lv_obj_t * ui_ScreenColor;
lv_obj_t * ui_Label29;
void ui_event_Button32(lv_event_t * e);
lv_obj_t * ui_Button32;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Button16;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Button17;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Container5;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
void ui_event_Button31(lv_event_t * e);
lv_obj_t * ui_Button31;
lv_obj_t * ui_Label36;
void ui_event_Container6(lv_event_t * e);
lv_obj_t * ui_Container6;
void ui_event_Container7(lv_event_t * e);
lv_obj_t * ui_Container7;
void ui_event_Container8(lv_event_t * e);
lv_obj_t * ui_Container8;
void ui_event_SliderRed(lv_event_t * e);
lv_obj_t * ui_SliderRed;
lv_obj_t * ui_LabelRed;
void ui_event_SliderGreen(lv_event_t * e);
lv_obj_t * ui_SliderGreen;
lv_obj_t * ui_LabelGreen;
void ui_event_SliderBlue(lv_event_t * e);
lv_obj_t * ui_SliderBlue;
lv_obj_t * ui_LabelBlue;
lv_obj_t * ui_Container9;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenOff
void ui_ScreenOff_screen_init(void);
void ui_event_ScreenOff(lv_event_t * e);
lv_obj_t * ui_ScreenOff;
lv_obj_t * ui_PanelOff;
lv_obj_t * ui_Label15;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label16;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Label17;
lv_obj_t * ui_PanelOn;
lv_obj_t * ui_Label27;
void ui_event_Button19(lv_event_t * e);
lv_obj_t * ui_Button19;
lv_obj_t * ui_Label28;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label46;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1738052006[1] = {&ui_img_100498730};
const lv_img_dsc_t * ui_imgset_683649883[1] = {&ui_img_1793113324};
const lv_img_dsc_t * ui_imgset_1527936714[1] = {&ui_img_1276658041};
const lv_img_dsc_t * ui_imgset_633900246[12] = {&ui_img_2022944295, &ui_img_1965946780, &ui_img_1247291337, &ui_img_941216143, &ui_img_140513036, &ui_img_1294863193, &ui_img_213134014, &ui_img_1543939845, &ui_img_2022945322, &ui_img_1965945753, &ui_img_941217166, &ui_img_140512013};
const lv_img_dsc_t * ui_imgset_1151499468[1] = {&ui_img_460647138};
const lv_img_dsc_t * ui_imgset_1174099236[1] = {&ui_img_1426255264};
const lv_img_dsc_t * ui_imgset_883720742[1] = {&ui_img_1979958042};
const lv_img_dsc_t * ui_imgset_482487908[9] = {&ui_img_765407899, &ui_img_37325770, &ui_img_1119054949, &ui_img_105684628, &ui_img_1187413807, &ui_img_1493484901, &ui_img_1719753216, &ui_img_1847131951, &ui_img_1366106166};
const lv_img_dsc_t * ui_imgset_1641994817[1] = {&ui_img_63382631};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void sec_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void secDot_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 35000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 600, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void PanelButton_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 64);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void PanelDisplay_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -140, -198);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        sec_Animation(ui_LabelSec, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ScreenHomeLoaded(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenQR, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_ScreenQR_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenColor, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ScreenColor_screen_init);
    }
}

void ui_event_Container4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        sleepButton(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_ScreenSleep, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSleep_screen_init);
        screenSleepIntro(e);
    }
}

void ui_event_Image20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenOff, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenOff_screen_init);
        _ui_flag_modify(ui_PanelOff, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBright, target, "", "");
        pwmChangeSlider(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        led1Long(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton1(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        led2Long(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton2(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        led3Long(e);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton3(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton4(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        led4Long(e);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button5, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton5(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        led5Long(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button6, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton6(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        led6Long(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button7, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton7(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        led7Long(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_Button8, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton8(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        led8Long(e);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button9, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        ledButton9(e);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button10, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        tvButton(e);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button11, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        frigeButton(e);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button12, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        invButton(e);
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brightSlide(e);
    }
}

void ui_event_PanelMessage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        panelMessageClick(e);
    }
}

void ui_event_ContainerWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifiClick(e);
    }
}

void ui_event_ContainerLock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        gestureLockUp(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        gestureLockDown(e);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brightQR(e);
    }
}

void ui_event_Container2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ScreenHome_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenColor, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_ScreenColor_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        masterModeSelect(e);
    }
}

void ui_event_SwitchNetwork(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        networkSelect(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Label41, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_SpinnerHotSpot, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_Label41, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_SpinnerHotSpot, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Label41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hotSpotSelect(e);
    }
}

void ui_event_TextAreaSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ssidClick(e);
        _ui_flag_modify(ui_RollerHotSpot, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TextAreaPSWD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pswdClick(e);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        keyboardClick(e);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        keyboardClick(e);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        networkSave(e);
        _ui_flag_modify(ui_PanelNetwork, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelNetwork, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_RollerHotSpot, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_RollerHotSpot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        wifiPick(e);
    }
}

void ui_event_ScreenSleep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        chgScreen2(e);
    }
}

void ui_event_Roller4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_Roller4, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SleepTimeSave(e);
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Button22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_Roller1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_ScreenColor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        chgScreen2(e);
        _ui_screen_change(&ui_ScreenQR, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ScreenQR_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Button32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        colorSave(e);
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Button31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        colorReset(e);
    }
}

void ui_event_Container6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        backGroundCheck(e);
    }
}

void ui_event_Container7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        switchOnCheck(e);
    }
}

void ui_event_Container8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        switchOffCheck(e);
    }
}

void ui_event_SliderRed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SliderRed(e);
        _ui_slider_set_text_value(ui_LabelRed, target, "", "");
    }
}

void ui_event_SliderGreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SliderGreen(e);
        _ui_slider_set_text_value(ui_LabelGreen, target, "", "");
    }
}

void ui_event_SliderBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SliderBlue(e);
        _ui_slider_set_text_value(ui_LabelBlue, target, "", "");
    }
}

void ui_event_ScreenOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        powerReconnection(e);
        _ui_flag_modify(ui_PanelOn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        powerOff(e);
        _ui_flag_modify(ui_PanelOff, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_Button19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        powerOnProcess(e);
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 0, &ui_ScreenHome_screen_init);
        _ui_flag_modify(ui_PanelOn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelOn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        powerOff(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenHome_screen_init();
    ui_ScreenQR_screen_init();
    ui_ScreenSleep_screen_init();
    ui_ScreenColor_screen_init();
    ui_ScreenOff_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenHome);
}
