// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_AuToHomes_SC01

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ScreenHomeLoaded(lv_event_t * e);
void sleepButton(lv_event_t * e);
void screenSleepIntro(lv_event_t * e);
void pwmChangeSlider(lv_event_t * e);
void led1Long(lv_event_t * e);
void ledButton1(lv_event_t * e);
void led2Long(lv_event_t * e);
void ledButton2(lv_event_t * e);
void led3Long(lv_event_t * e);
void ledButton3(lv_event_t * e);
void ledButton4(lv_event_t * e);
void led4Long(lv_event_t * e);
void ledButton5(lv_event_t * e);
void led5Long(lv_event_t * e);
void ledButton6(lv_event_t * e);
void led6Long(lv_event_t * e);
void ledButton7(lv_event_t * e);
void led7Long(lv_event_t * e);
void ledButton8(lv_event_t * e);
void led8Long(lv_event_t * e);
void ledButton9(lv_event_t * e);
void tvButton(lv_event_t * e);
void frigeButton(lv_event_t * e);
void invButton(lv_event_t * e);
void brightSlide(lv_event_t * e);
void panelMessageClick(lv_event_t * e);
void wifiClick(lv_event_t * e);
void gestureLockUp(lv_event_t * e);
void gestureLockDown(lv_event_t * e);
void brightQR(lv_event_t * e);
void masterModeSelect(lv_event_t * e);
void networkSelect(lv_event_t * e);
void hotSpotSelect(lv_event_t * e);
void ssidClick(lv_event_t * e);
void pswdClick(lv_event_t * e);
void keyboardClick(lv_event_t * e);
void networkSave(lv_event_t * e);
void wifiPick(lv_event_t * e);
void chgScreen2(lv_event_t * e);
void SleepTimeSave(lv_event_t * e);
void colorSave(lv_event_t * e);
void colorReset(lv_event_t * e);
void backGroundCheck(lv_event_t * e);
void switchOnCheck(lv_event_t * e);
void switchOffCheck(lv_event_t * e);
void SliderRed(lv_event_t * e);
void SliderGreen(lv_event_t * e);
void SliderBlue(lv_event_t * e);
void powerReconnection(lv_event_t * e);
void powerOff(lv_event_t * e);
void powerOnProcess(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
