// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_AuToHomes_SC01

#include "ui.h"

void ui_ScreenQR_screen_init(void)
{
    ui_ScreenQR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 260);
    lv_obj_set_y(ui_Label23, -15);
    lv_obj_set_align(ui_Label23, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label23, "와이파이 네트워크:");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSSID = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_LabelSSID, 230);
    lv_obj_set_height(ui_LabelSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSSID, 121);
    lv_obj_set_y(ui_LabelSSID, 15);
    lv_obj_set_align(ui_LabelSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSSID, "오토홈스 V6.0-CB-043");
    lv_obj_set_style_text_align(ui_LabelSSID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSSID, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelSSID, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelSSID, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelSSID, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPSWD = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_LabelPSWD, 230);
    lv_obj_set_height(ui_LabelPSWD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPSWD, 121);
    lv_obj_set_y(ui_LabelPSWD, 85);
    lv_obj_set_align(ui_LabelPSWD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPSWD, "16250212043");
    lv_obj_set_style_text_align(ui_LabelPSWD, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPSWD, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelPSWD, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelPSWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPSWD, lv_color_hex(0x00B53B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPSWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelPSWD, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 260);
    lv_obj_set_y(ui_Label24, 55);
    lv_obj_set_align(ui_Label24, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label24, "와이파이 비밀번호:");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageQR = lv_img_create(ui_ScreenQR);
    lv_img_set_src(ui_ImageQR, &ui_img_1366106166);
    lv_obj_set_width(ui_ImageQR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageQR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageQR, -111);
    lv_obj_set_y(ui_ImageQR, 1);
    lv_obj_set_align(ui_ImageQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageQR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageQR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpinnerHotSpot = lv_spinner_create(ui_ScreenQR, 1000, 90);
    lv_obj_set_width(ui_SpinnerHotSpot, 80);
    lv_obj_set_height(ui_SpinnerHotSpot, 80);
    lv_obj_set_x(ui_SpinnerHotSpot, -111);
    lv_obj_set_y(ui_SpinnerHotSpot, 1);
    lv_obj_set_align(ui_SpinnerHotSpot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpinnerHotSpot, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpinnerHotSpot, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_ScreenQR);
    lv_slider_set_range(ui_Slider2, 10, 255);
    lv_slider_set_value(ui_Slider2, 127, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 215);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 121);
    lv_obj_set_y(ui_Slider2, 120);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);


    ui_Container2 = lv_obj_create(ui_ScreenQR);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 466);
    lv_obj_set_height(ui_Container2, 246);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -37);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Label37 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 412);
    lv_obj_set_y(ui_Label37, -110);
    lv_obj_set_align(ui_Label37, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label37, "마스타");
    lv_obj_set_style_text_align(ui_Label37, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -152);
    lv_obj_set_y(ui_Label39, -110);
    lv_obj_set_align(ui_Label39, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label39, "슬레이브");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -152);
    lv_obj_set_y(ui_Label40, -65);
    lv_obj_set_align(ui_Label40, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label40, "와이파이");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_ScreenQR);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 127);
    lv_obj_set_y(ui_Switch1, -110);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);       /// States


    ui_SwitchNetwork = lv_switch_create(ui_ScreenQR);
    lv_obj_set_width(ui_SwitchNetwork, 50);
    lv_obj_set_height(ui_SwitchNetwork, 25);
    lv_obj_set_x(ui_SwitchNetwork, 127);
    lv_obj_set_y(ui_SwitchNetwork, -65);
    lv_obj_set_align(ui_SwitchNetwork, LV_ALIGN_CENTER);


    ui_Label41 = lv_label_create(ui_ScreenQR);
    lv_obj_set_width(ui_Label41, 70);
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 403);
    lv_obj_set_y(ui_Label41, -65);
    lv_obj_set_align(ui_Label41, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label41, "핫스팟");
    lv_obj_add_flag(ui_Label41, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_Label41, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_Label41, 2, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_Label41, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PanelNetwork = lv_obj_create(ui_ScreenQR);
    lv_obj_set_width(ui_PanelNetwork, 480);
    lv_obj_set_height(ui_PanelNetwork, 320);
    lv_obj_set_align(ui_PanelNetwork, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelNetwork, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaSSID = lv_textarea_create(ui_PanelNetwork);
    lv_obj_set_width(ui_TextAreaSSID, 270);
    lv_obj_set_height(ui_TextAreaSSID, 45);
    lv_obj_set_x(ui_TextAreaSSID, -10);
    lv_obj_set_y(ui_TextAreaSSID, -130);
    lv_obj_set_align(ui_TextAreaSSID, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaSSID, 100);
    lv_textarea_set_placeholder_text(ui_TextAreaSSID, "핫스팟 네트워크");
    lv_obj_clear_flag(ui_TextAreaSSID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TextAreaSSID, lv_color_hex(0xF2FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaSSID, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextAreaSSID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextAreaSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextAreaSSID, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextAreaSSID, 2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaPSWD = lv_textarea_create(ui_PanelNetwork);
    lv_obj_set_width(ui_TextAreaPSWD, 270);
    lv_obj_set_height(ui_TextAreaPSWD, 45);
    lv_obj_set_x(ui_TextAreaPSWD, -10);
    lv_obj_set_y(ui_TextAreaPSWD, -80);
    lv_obj_set_align(ui_TextAreaPSWD, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaPSWD, 100);
    lv_textarea_set_placeholder_text(ui_TextAreaPSWD, "핫스팟 비밀번호");
    lv_obj_clear_flag(ui_TextAreaPSWD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TextAreaPSWD, lv_color_hex(0xF2FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaPSWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPSWD, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TextAreaPSWD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TextAreaPSWD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TextAreaPSWD, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TextAreaPSWD, 2, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Keyboard1 = lv_keyboard_create(ui_PanelNetwork);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_Keyboard1, 478);
    lv_obj_set_height(ui_Keyboard1, 200);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 57);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Keyboard2 = lv_keyboard_create(ui_PanelNetwork);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 478);
    lv_obj_set_height(ui_Keyboard2, 200);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 57);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label42 = lv_label_create(ui_PanelNetwork);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -194);
    lv_obj_set_y(ui_Label42, -130);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "네트워크 :");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_PanelNetwork);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -194);
    lv_obj_set_y(ui_Label43, -80);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "비밀번호 :");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_PanelNetwork);
    lv_obj_set_width(ui_Button13, 78);
    lv_obj_set_height(ui_Button13, 41);
    lv_obj_set_x(ui_Button13, 185);
    lv_obj_set_y(ui_Button13, -130);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_state(ui_Button13, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -194);
    lv_obj_set_y(ui_Label44, -130);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "저장");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_PanelNetwork);
    lv_obj_set_width(ui_Button14, 78);
    lv_obj_set_height(ui_Button14, 41);
    lv_obj_set_x(ui_Button14, 185);
    lv_obj_set_y(ui_Button14, -80);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label45 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -194);
    lv_obj_set_y(ui_Label45, -130);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "취소");
    lv_obj_set_style_text_font(ui_Label45, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerHotSpot = lv_roller_create(ui_ScreenQR);
    lv_roller_set_options(ui_RollerHotSpot, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerHotSpot, 347);
    lv_obj_set_height(ui_RollerHotSpot, 171);
    lv_obj_set_x(ui_RollerHotSpot, -52);
    lv_obj_set_y(ui_RollerHotSpot, 41);
    lv_obj_set_align(ui_RollerHotSpot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerHotSpot, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_RollerHotSpot, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerHotSpot, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerHotSpot, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerHotSpot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerHotSpot, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_RollerHotSpot, lv_color_hex(0x00FF45), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_RollerHotSpot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_RollerHotSpot, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_RollerHotSpot, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_RollerHotSpot, &ui_font_SOYOMapleBold18, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerHotSpot, lv_color_hex(0xFEF600), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerHotSpot, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerHotSpot, 2, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RollerHotSpot, LV_BORDER_SIDE_FULL, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container2, ui_event_Container2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchNetwork, ui_event_SwitchNetwork, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label41, ui_event_Label41, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSSID, ui_event_TextAreaSSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPSWD, ui_event_TextAreaPSWD, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextAreaSSID);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextAreaPSWD);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RollerHotSpot, ui_event_RollerHotSpot, LV_EVENT_ALL, NULL);

}
