// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_LM_LED_8048S050-V3.0

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ScreenHomeLoaded(lv_event_t * e);
void logoChangeClick(lv_event_t * e);
void logoClick(lv_event_t * e);
void settingClick(lv_event_t * e);
void wifiClick(lv_event_t * e);
void pwmChangeSlider(lv_event_t * e);
void setLEDPwm(lv_event_t * e);
void BGBright(lv_event_t * e);
void setBright(lv_event_t * e);
void led1Left(lv_event_t * e);
void ledButton1(lv_event_t * e);
void ledButton4(lv_event_t * e);
void led4Left(lv_event_t * e);
void led2Left(lv_event_t * e);
void ledButton2(lv_event_t * e);
void led2GestureRight(lv_event_t * e);
void ledButton5(lv_event_t * e);
void led5Left(lv_event_t * e);
void led3Left(lv_event_t * e);
void ledButton3(lv_event_t * e);
void led3GestureRight(lv_event_t * e);
void tvButton(lv_event_t * e);
void panelMessageClick(lv_event_t * e);
void tvOutButton(lv_event_t * e);
void brightQR(lv_event_t * e);
void masterModeSelect(lv_event_t * e);
void ScreenUserSetLoad(lv_event_t * e);
void userSetting(lv_event_t * e);
void userSettingCancel(lv_event_t * e);
void rollerNeoMode(lv_event_t * e);
void SliderRed(lv_event_t * e);
void SliderRedReleased(lv_event_t * e);
void SliderGreen(lv_event_t * e);
void SliderGreenReleased(lv_event_t * e);
void SliderBlue(lv_event_t * e);
void SliderBlueReleased(lv_event_t * e);
void neoMode1(lv_event_t * e);
void neoMode2(lv_event_t * e);
void neoMode3(lv_event_t * e);
void neoMode4(lv_event_t * e);
void neoMode5(lv_event_t * e);
void ScreenSettingLoad(lv_event_t * e);
void factorySetting(lv_event_t * e);
void factorySettingCancel(lv_event_t * e);
void switchMood(lv_event_t * e);
void switchSide(lv_event_t * e);
void logoFlagReset(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
