// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: esp32_ST7789V3

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel4, 318);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -60);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0xFBFE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -127);
    lv_obj_set_y(ui_Label13, -12);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "리프트 1 :");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_liftValue1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_liftValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_liftValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_liftValue1, -211);
    lv_obj_set_y(ui_liftValue1, -12);
    lv_obj_set_align(ui_liftValue1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_liftValue1, "0.0");
    lv_obj_set_style_text_font(ui_liftValue1, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 79);
    lv_obj_set_y(ui_Label15, -12);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "A");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -127);
    lv_obj_set_y(ui_Label14, 12);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "리프트 3 :");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_liftValue2 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_liftValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_liftValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_liftValue2, -53);
    lv_obj_set_y(ui_liftValue2, -12);
    lv_obj_set_align(ui_liftValue2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_liftValue2, "0.0");
    lv_obj_set_style_text_font(ui_liftValue2, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 79);
    lv_obj_set_y(ui_Label16, 12);
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "A");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 32);
    lv_obj_set_y(ui_Label17, -12);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "리프트 2 :");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_liftValue3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_liftValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_liftValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_liftValue3, -211);
    lv_obj_set_y(ui_liftValue3, 12);
    lv_obj_set_align(ui_liftValue3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_liftValue3, "0.0");
    lv_obj_set_style_text_font(ui_liftValue3, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 239);
    lv_obj_set_y(ui_Label18, -12);
    lv_obj_set_align(ui_Label18, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label18, "A");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 32);
    lv_obj_set_y(ui_Label19, 12);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "리프트 2 :");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_liftValue4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_liftValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_liftValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_liftValue4, -53);
    lv_obj_set_y(ui_liftValue4, 12);
    lv_obj_set_align(ui_liftValue4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_liftValue4, "0.0");
    lv_obj_set_style_text_font(ui_liftValue4, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 239);
    lv_obj_set_y(ui_Label20, 12);
    lv_obj_set_align(ui_Label20, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label20, "A");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refDisp1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_refDisp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refDisp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_refDisp1, 93);
    lv_obj_set_y(ui_refDisp1, -12);
    lv_obj_set_align(ui_refDisp1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_refDisp1, "(0.0A)");
    lv_obj_set_style_text_color(ui_refDisp1, lv_color_hex(0xFCFF12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_refDisp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_refDisp1, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refDisp3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_refDisp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refDisp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_refDisp3, 93);
    lv_obj_set_y(ui_refDisp3, 12);
    lv_obj_set_align(ui_refDisp3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_refDisp3, "(0.0A)");
    lv_obj_set_style_text_color(ui_refDisp3, lv_color_hex(0xFCFF12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_refDisp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_refDisp3, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refDisp2 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_refDisp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refDisp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_refDisp2, 254);
    lv_obj_set_y(ui_refDisp2, -12);
    lv_obj_set_align(ui_refDisp2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_refDisp2, "(0.0A)");
    lv_obj_set_style_text_color(ui_refDisp2, lv_color_hex(0xFCFF12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_refDisp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_refDisp2, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refDisp4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_refDisp4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refDisp4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_refDisp4, 254);
    lv_obj_set_y(ui_refDisp4, 12);
    lv_obj_set_align(ui_refDisp4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_refDisp4, "(0.0A)");
    lv_obj_set_style_text_color(ui_refDisp4, lv_color_hex(0xFCFF12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_refDisp4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_refDisp4, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea1, 320);
    lv_obj_set_height(ui_TextArea1, 119);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, 26);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);



}
