// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SQL_Marre_ST7789-V3

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void panelVolt(lv_event_t * e);
void voltPlus(lv_event_t * e);
void voltMinus(lv_event_t * e);
void voltSave(lv_event_t * e);
void Screen2Load(lv_event_t * e);
void opacityChange(lv_event_t * e);
void networkScreenLoaded(lv_event_t * e);
void networkSelectSwitch(lv_event_t * e);
void btnPowerOnExeSave(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
