// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL_LM_SEAT_8048S050

#ifndef _SQL_LM_SEAT_8048S050_UI_H
#define _SQL_LM_SEAT_8048S050_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

void seatUp_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
void ui_event_Container1(lv_event_t * e);
extern lv_obj_t * ui_Container1;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_ImageNetwork;
void ui_event_ContainerWiFi(lv_event_t * e);
extern lv_obj_t * ui_ContainerWiFi;
extern lv_obj_t * ui_ImageWiFi;
extern lv_obj_t * ui_LabelSL;
void ui_event_PanelMessage(lv_event_t * e);
extern lv_obj_t * ui_PanelMessage;
extern lv_obj_t * ui_LabelMessage;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image4;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image5;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_ContainerL3;
extern lv_obj_t * ui_ContainerL2;
extern lv_obj_t * ui_ContainerL1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_ContainerC1;
extern lv_obj_t * ui_ContainerC2;
extern lv_obj_t * ui_ContainerC3;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_ContainerR3;
extern lv_obj_t * ui_ContainerR2;
extern lv_obj_t * ui_ContainerR1;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
void ui_event_ButtonSet(lv_event_t * e);
extern lv_obj_t * ui_ButtonSet;
extern lv_obj_t * ui_Label2;
void ui_event_ButtonSave1(lv_event_t * e);
extern lv_obj_t * ui_ButtonSave1;
extern lv_obj_t * ui_Label1;
void ui_event_ButtonSave2(lv_event_t * e);
extern lv_obj_t * ui_ButtonSave2;
extern lv_obj_t * ui_Label4;
void ui_event_ButtonSet2(lv_event_t * e);
extern lv_obj_t * ui_ButtonSet2;
extern lv_obj_t * ui_Label7;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Panel2;
void ui_event_ButtonSet1(lv_event_t * e);
extern lv_obj_t * ui_ButtonSet1;
extern lv_obj_t * ui_Label3;
void ui_event_ButtonCancel1(lv_event_t * e);
extern lv_obj_t * ui_ButtonCancel1;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenQR
void ui_ScreenQR_screen_init(void);
extern lv_obj_t * ui_ScreenQR;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_LabelSSID;
extern lv_obj_t * ui_LabelPSWD;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_ImageQR;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label39;
void ui_event_Container2(lv_event_t * e);
extern lv_obj_t * ui_Container2;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenLogo
void ui_ScreenLogo_screen_init(void);
void ui_event_ScreenLogo(lv_event_t * e);
extern lv_obj_t * ui_ScreenLogo;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenLogo2
void ui_ScreenLogo2_screen_init(void);
void ui_event_ScreenLogo2(lv_event_t * e);
extern lv_obj_t * ui_ScreenLogo2;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1552868417);    // assets/seat-66.png
LV_IMG_DECLARE(ui_img_1332874776);    // assets/LM-Logo.png
LV_IMG_DECLARE(ui_img_420585491);    // assets/Icon-NET-26.png
LV_IMG_DECLARE(ui_img_941217166);    // assets/Icon-30.png
LV_IMG_DECLARE(ui_img_1285933598);    // assets/seat-70.png
LV_IMG_DECLARE(ui_img_149442631);    // assets/seat-71.png
LV_IMG_DECLARE(ui_img_932286548);    // assets/seat-72.png
LV_IMG_DECLARE(ui_img_1371686955);    // assets/seat-1-67-71.png
LV_IMG_DECLARE(ui_img_2014015727);    // assets/seat-73.png
LV_IMG_DECLARE(ui_img_1187412780);    // assets/QR-Code-009.png
LV_IMG_DECLARE(ui_img_2128645090);    // assets/LM-Logo 2.png
LV_IMG_DECLARE(ui_img_618194214);    // assets/logo-3.png
LV_IMG_DECLARE(ui_img_campingcar_icons_png);    // assets/CampingCar_Icons.png
LV_IMG_DECLARE(ui_img_1446094990);    // assets/logo-65.png
LV_IMG_DECLARE(ui_img_1371685930);    // assets/seat-1-67-70.png
LV_IMG_DECLARE(ui_img_37324743);    // assets/QR-Code-006.png
LV_IMG_DECLARE(ui_img_1119053922);    // assets/QR-Code-007.png
LV_IMG_DECLARE(ui_img_105683601);    // assets/QR-Code-008.png
LV_IMG_DECLARE(ui_img_1493487978);    // assets/QR-Code-010.png

// FONTS
LV_FONT_DECLARE(ui_font_DigitalPlaySt12);
LV_FONT_DECLARE(ui_font_SOYOMapleBold12);
LV_FONT_DECLARE(ui_font_SOYOMapleBold14);
LV_FONT_DECLARE(ui_font_SOYOMapleBold18);
LV_FONT_DECLARE(ui_font_SOYOMapleBold22);
LV_FONT_DECLARE(ui_font_SOYOMapleBold26);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
