// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-WaveShare-V6.0

#ifndef _SQL_WAVESHARE_V6_0_UI_H
#define _SQL_WAVESHARE_V6_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

void sec_Animation(lv_obj_t * TargetObject, int delay);
void secDot_Animation(lv_obj_t * TargetObject, int delay);
void PanelButton_Animation(lv_obj_t * TargetObject, int delay);
void PanelDisplay_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_Container1;
void ui_event_ImageWiFi(lv_event_t * e);
extern lv_obj_t * ui_ImageWiFi;
void ui_event_LabelDay(lv_event_t * e);
extern lv_obj_t * ui_LabelDay;
extern lv_obj_t * ui_LabelAmPm;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_LabelSec;
extern lv_obj_t * ui_LabelMin;
extern lv_obj_t * ui_ImageMain;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_ImageNetwork;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
void ui_event_Container3(lv_event_t * e);
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_PanelDisplay;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_LabelVolt;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_LabelNowTemp;
extern lv_obj_t * ui_LabelSetTemp;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_BarClean;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_LabelClean;
extern lv_obj_t * ui_BarWaste;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_LabelWaste;
void ui_event_clnButton(lv_event_t * e);
extern lv_obj_t * ui_clnButton;
extern lv_obj_t * ui_Label41;
void ui_event_wstButton(lv_event_t * e);
extern lv_obj_t * ui_wstButton;
extern lv_obj_t * ui_Label32;
void ui_event_tempDownButton(lv_event_t * e);
extern lv_obj_t * ui_tempDownButton;
extern lv_obj_t * ui_Image20;
void ui_event_tempUpButton(lv_event_t * e);
extern lv_obj_t * ui_tempUpButton;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_PanelLED;
extern lv_obj_t * ui_LabelLED;
extern lv_obj_t * ui_LabelBright;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
void ui_event_SliderHeater(lv_event_t * e);
extern lv_obj_t * ui_SliderHeater;
void ui_event_SliderLiving(lv_event_t * e);
extern lv_obj_t * ui_SliderLiving;
void ui_event_heaterButton(lv_event_t * e);
extern lv_obj_t * ui_heaterButton;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label48;
void ui_event_livingButton(lv_event_t * e);
extern lv_obj_t * ui_livingButton;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_PanelOUT;
void ui_event_bunkerButton(lv_event_t * e);
extern lv_obj_t * ui_bunkerButton;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label30;
void ui_event_outButton2(lv_event_t * e);
extern lv_obj_t * ui_outButton2;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_outLabel2;
void ui_event_outButton3(lv_event_t * e);
extern lv_obj_t * ui_outButton3;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_outLabel3;
void ui_event_outButton4(lv_event_t * e);
extern lv_obj_t * ui_outButton4;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_outLabel4;
void ui_event_boilerButton(lv_event_t * e);
extern lv_obj_t * ui_boilerButton;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_outLabel5;
void ui_event_outButton6(lv_event_t * e);
extern lv_obj_t * ui_outButton6;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Container5;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_ledLabel1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_ledLabel2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_ledLabel3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_ledLabel4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_ledLabel5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_ledLabel6;
void ui_event_outButton1(lv_event_t * e);
extern lv_obj_t * ui_outButton1;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_outLabel1;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label15;
void ui_event_invButton(lv_event_t * e);
extern lv_obj_t * ui_invButton;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label333;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenQR
void ui_ScreenQR_screen_init(void);
extern lv_obj_t * ui_ScreenQR;
extern lv_obj_t * ui_Label23;
void ui_event_LabelSSID(lv_event_t * e);
extern lv_obj_t * ui_LabelSSID;
extern lv_obj_t * ui_LabelPSWD;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_ImageQR;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
void ui_event_Container2(lv_event_t * e);
extern lv_obj_t * ui_Container2;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_LabelBtnInit;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenClock
void ui_ScreenClock_screen_init(void);
extern lv_obj_t * ui_ScreenClock;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_LabelNowTime;
void ui_event_RollerYear(lv_event_t * e);
extern lv_obj_t * ui_RollerYear;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_RollerMonth;
extern lv_obj_t * ui_Label4;
void ui_event_RollerDay(lv_event_t * e);
extern lv_obj_t * ui_RollerDay;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_RollerHour;
extern lv_obj_t * ui_Label6;
void ui_event_RollerMin(lv_event_t * e);
extern lv_obj_t * ui_RollerMin;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_941223316);    // assets/Icon-90.png
LV_IMG_DECLARE(ui_img_network_png);    // assets/network.png
LV_IMG_DECLARE(ui_img_1965945753);    // assets/Icon-28.png
LV_IMG_DECLARE(ui_img_213134014);    // assets/Icon-23.png
LV_IMG_DECLARE(ui_img_100498730);    // assets/Battery-09.png
LV_IMG_DECLARE(ui_img_63382631);    // assets/Temp-10.png
LV_IMG_DECLARE(ui_img_1768995494);    // assets/Arrow-Black.png
LV_IMG_DECLARE(ui_img_140505863);    // assets/Icon-91.png
LV_IMG_DECLARE(ui_img_213141187);    // assets/Icon-93.png
LV_IMG_DECLARE(ui_img_969258056);    // assets/Icon-96-96.png
LV_IMG_DECLARE(ui_img_199453633);    // assets/Icon-38-44.png
LV_IMG_DECLARE(ui_img_199452608);    // assets/Icon-38-45.png
LV_IMG_DECLARE(ui_img_2077020016);    // assets/Icon-38-38.png
LV_IMG_DECLARE(ui_img_1190290745);    // assets/Icon-46.png
LV_IMG_DECLARE(ui_img_199447235);    // assets/Icon-38-42.png
LV_IMG_DECLARE(ui_img_1965946780);    // assets/Icon-18.png
LV_IMG_DECLARE(ui_img_912627908);    // assets/Icon-38-40-40.png
LV_IMG_DECLARE(ui_img_2077021041);    // assets/Icon-38-39.png
LV_IMG_DECLARE(ui_img_1543939845);    // assets/Icon-24.png
LV_IMG_DECLARE(ui_img_1543932672);    // assets/Icon-94.png
LV_IMG_DECLARE(ui_img_1294863193);    // assets/Icon-22.png
LV_IMG_DECLARE(ui_img_1847143228);    // assets/QR-Code-092.png
LV_IMG_DECLARE(ui_img_638533140);    // assets/timer-94-94.png
LV_IMG_DECLARE(ui_img_199448260);    // assets/Icon-38-41.png
LV_IMG_DECLARE(ui_img_1294870366);    // assets/Icon-92.png
LV_IMG_DECLARE(ui_img_1669305445);    // assets/Icon-95.png

// FONTS
LV_FONT_DECLARE(ui_font_DigitalPlaySt12);
LV_FONT_DECLARE(ui_font_SOYOMapleBold12);
LV_FONT_DECLARE(ui_font_SOYOMapleBold14);
LV_FONT_DECLARE(ui_font_SOYOMapleBold18);
LV_FONT_DECLARE(ui_font_SOYOMapleBold22);
LV_FONT_DECLARE(ui_font_SOYOMapleBold26);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
