// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SQL-WaveShare-V6.0

#include "ui.h"

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 800);
    lv_obj_set_height(ui_Container1, 41);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -220);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWiFi = lv_img_create(ui_Container1);
    lv_img_set_src(ui_ImageWiFi, &ui_img_wifi_png);
    lv_obj_set_width(ui_ImageWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWiFi, 366);
    lv_obj_set_y(ui_ImageWiFi, -2);
    lv_obj_set_align(ui_ImageWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWiFi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageWiFi, 200);

    ui_LabelDay = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDay, -300);
    lv_obj_set_y(ui_LabelDay, 0);
    lv_obj_set_align(ui_LabelDay, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelDay, "20년 1월 15일 토요일");
    lv_obj_add_flag(ui_LabelDay, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_LabelDay, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAmPm = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelAmPm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAmPm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAmPm, 126);
    lv_obj_set_y(ui_LabelAmPm, 2);
    lv_obj_set_align(ui_LabelAmPm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAmPm, "Am");
    lv_obj_set_style_text_font(ui_LabelAmPm, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -228);
    lv_obj_set_y(ui_LabelTime, 0);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTime, "22");
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSec = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelSec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSec, 180);
    lv_obj_set_y(ui_LabelSec, 0);
    lv_obj_set_align(ui_LabelSec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSec, ":");
    lv_obj_set_style_text_font(ui_LabelSec, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMin = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMin, 589);
    lv_obj_set_y(ui_LabelMin, 0);
    lv_obj_set_align(ui_LabelMin, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelMin, "58");
    lv_obj_set_style_text_font(ui_LabelMin, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMain = lv_img_create(ui_Container1);
    lv_img_set_src(ui_ImageMain, &ui_img_941223316);
    lv_obj_set_width(ui_ImageMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageMain, -378);
    lv_obj_set_y(ui_ImageMain, 0);
    lv_obj_set_align(ui_ImageMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMain, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_ImageMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageMain, 250);

    ui_Label27 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label27, 127);
    lv_obj_set_height(ui_Label27, 20);
    lv_obj_set_x(ui_Label27, 50);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label27, "풀하우스캠핑카");
    lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageNetwork = lv_img_create(ui_Container1);
    lv_img_set_src(ui_ImageNetwork, &ui_img_network_png);
    lv_obj_set_width(ui_ImageNetwork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageNetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageNetwork, 310);
    lv_obj_set_y(ui_ImageNetwork, 0);
    lv_obj_set_align(ui_ImageNetwork, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNetwork, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageNetwork, 200);

    ui_Image22 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image22, &ui_img_1965945753);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, -150);
    lv_obj_set_y(ui_Image22, 0);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image22, 180);

    ui_Image23 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image23, &ui_img_213134014);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, -150);
    lv_obj_set_y(ui_Image23, 0);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image23, 180);

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 80);
    lv_obj_set_height(ui_Container3, 45);
    lv_obj_set_x(ui_Container3, -150);
    lv_obj_set_y(ui_Container3, 0);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelDisplay = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelDisplay, 164);
    lv_obj_set_height(ui_PanelDisplay, 434);
    lv_obj_set_x(ui_PanelDisplay, -316);
    lv_obj_set_y(ui_PanelDisplay, 21);
    lv_obj_set_align(ui_PanelDisplay, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDisplay, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDisplay, lv_color_hex(0x292C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_PanelDisplay);
    lv_img_set_src(ui_Image3, &ui_img_100498730);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -44);
    lv_obj_set_y(ui_Image3, -175);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 180);

    ui_LabelVolt = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVolt, 60);
    lv_obj_set_y(ui_LabelVolt, -172);
    lv_obj_set_align(ui_LabelVolt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelVolt, "--.-  V");
    lv_obj_set_style_text_font(ui_LabelVolt, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_PanelDisplay);
    lv_img_set_src(ui_Image4, &ui_img_63382631);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -50);
    lv_obj_set_y(ui_Image4, -111);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 180);

    ui_LabelNowTemp = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelNowTemp, 100);
    lv_obj_set_height(ui_LabelNowTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNowTemp, 10);
    lv_obj_set_y(ui_LabelNowTemp, -123);
    lv_obj_set_align(ui_LabelNowTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelNowTemp, "--.- °C");
    lv_obj_set_style_text_align(ui_LabelNowTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNowTemp, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSetTemp = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelSetTemp, 100);
    lv_obj_set_height(ui_LabelSetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetTemp, 10);
    lv_obj_set_y(ui_LabelSetTemp, -97);
    lv_obj_set_align(ui_LabelSetTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelSetTemp, "25.0 °C");
    lv_obj_set_style_text_color(ui_LabelSetTemp, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSetTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetTemp, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_PanelDisplay);
    lv_slider_set_range(ui_Slider3, 1, 255);
    lv_slider_set_value(ui_Slider3, 255, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 164);
    lv_obj_set_height(ui_Slider3, 434);
    lv_obj_set_x(ui_Slider3, 0);
    lv_obj_set_y(ui_Slider3, -1);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BarClean = lv_bar_create(ui_PanelDisplay);
    lv_obj_set_width(ui_BarClean, 42);
    lv_obj_set_height(ui_BarClean, 130);
    lv_obj_set_x(ui_BarClean, -43);
    lv_obj_set_y(ui_BarClean, 70);
    lv_obj_set_align(ui_BarClean, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BarClean, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BarClean, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarClean, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarClean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarClean, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarClean, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarClean, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarClean, lv_color_hex(0x1150FA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarClean, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_BarClean);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 5);
    lv_obj_set_y(ui_Label33, 11);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "청수");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClean = lv_label_create(ui_BarClean);
    lv_obj_set_width(ui_LabelClean, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClean, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelClean, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClean, "---");
    lv_obj_set_style_text_color(ui_LabelClean, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClean, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarWaste = lv_bar_create(ui_PanelDisplay);
    lv_obj_set_width(ui_BarWaste, 42);
    lv_obj_set_height(ui_BarWaste, 130);
    lv_obj_set_x(ui_BarWaste, 40);
    lv_obj_set_y(ui_BarWaste, 70);
    lv_obj_set_align(ui_BarWaste, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BarWaste, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BarWaste, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BarWaste, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarWaste, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarWaste, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarWaste, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarWaste, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarWaste, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarWaste, lv_color_hex(0x656161), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarWaste, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_BarWaste);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 5);
    lv_obj_set_y(ui_Label34, 11);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "오수");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWaste = lv_label_create(ui_BarWaste);
    lv_obj_set_width(ui_LabelWaste, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWaste, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWaste, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWaste, "---");
    lv_obj_set_style_text_color(ui_LabelWaste, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWaste, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWaste, &ui_font_SOYOMapleBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clnButton = lv_btn_create(ui_PanelDisplay);
    lv_obj_set_width(ui_clnButton, 69);
    lv_obj_set_height(ui_clnButton, 54);
    lv_obj_set_x(ui_clnButton, -43);
    lv_obj_set_y(ui_clnButton, 178);
    lv_obj_set_align(ui_clnButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_clnButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_clnButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clnButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_clnButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_clnButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_clnButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_clnButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_clnButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_clnButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_clnButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clnButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_clnButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label41 = lv_label_create(ui_clnButton);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "청수\n퇴수");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wstButton = lv_btn_create(ui_PanelDisplay);
    lv_obj_set_width(ui_wstButton, 69);
    lv_obj_set_height(ui_wstButton, 54);
    lv_obj_set_x(ui_wstButton, 40);
    lv_obj_set_y(ui_wstButton, 179);
    lv_obj_set_align(ui_wstButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wstButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wstButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wstButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_wstButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_wstButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_wstButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_wstButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_wstButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_wstButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_wstButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wstButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_wstButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label32 = lv_label_create(ui_wstButton);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "오수\n퇴수");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempDownButton = lv_btn_create(ui_PanelDisplay);
    lv_obj_set_width(ui_tempDownButton, 55);
    lv_obj_set_height(ui_tempDownButton, 55);
    lv_obj_set_x(ui_tempDownButton, -43);
    lv_obj_set_y(ui_tempDownButton, -43);
    lv_obj_set_align(ui_tempDownButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tempDownButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tempDownButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempDownButton,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tempDownButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_tempDownButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_tempDownButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempDownButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempDownButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_tempDownButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_tempDownButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_tempDownButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_tempDownButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempDownButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_tempDownButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image20 = lv_img_create(ui_tempDownButton);
    lv_img_set_src(ui_Image20, &ui_img_1768995494);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image20, 200);

    ui_tempUpButton = lv_btn_create(ui_PanelDisplay);
    lv_obj_set_width(ui_tempUpButton, 55);
    lv_obj_set_height(ui_tempUpButton, 55);
    lv_obj_set_x(ui_tempUpButton, 40);
    lv_obj_set_y(ui_tempUpButton, -43);
    lv_obj_set_align(ui_tempUpButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tempUpButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tempUpButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempUpButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_tempUpButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_tempUpButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_tempUpButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempUpButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempUpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_tempUpButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_tempUpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_tempUpButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_tempUpButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempUpButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_tempUpButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image21 = lv_img_create(ui_tempUpButton);
    lv_img_set_src(ui_Image21, &ui_img_1768995494);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image21, 1800);
    lv_img_set_zoom(ui_Image21, 200);

    ui_PanelLED = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelLED, 485);
    lv_obj_set_height(ui_PanelLED, 434);
    lv_obj_set_x(ui_PanelLED, 11);
    lv_obj_set_y(ui_PanelLED, 21);
    lv_obj_set_align(ui_PanelLED, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLED, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLED, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLED, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLED, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLED, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLED, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLED, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLED = lv_label_create(ui_PanelLED);
    lv_obj_set_width(ui_LabelLED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLED, -200);
    lv_obj_set_y(ui_LabelLED, 194);
    lv_obj_set_align(ui_LabelLED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLED, "전체등");
    lv_obj_set_style_text_font(ui_LabelLED, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBright = lv_label_create(ui_PanelLED);
    lv_obj_set_width(ui_LabelBright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBright, -200);
    lv_obj_set_y(ui_LabelBright, -194);
    lv_obj_set_align(ui_LabelBright, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBright, "100");
    lv_obj_set_style_text_font(ui_LabelBright, &ui_font_SOYOMapleBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_PanelLED);
    lv_slider_set_range(ui_Slider1, 1, 100);
    lv_slider_set_value(ui_Slider1, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 4);
    lv_obj_set_height(ui_Slider1, 320);
    lv_obj_set_x(ui_Slider1, -200);
    lv_obj_set_y(ui_Slider1, -1);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFA9F10), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFF0202), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Slider1, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Slider1, 13, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderHeater = lv_slider_create(ui_PanelLED);
    lv_slider_set_range(ui_SliderHeater, 20, 100);
    lv_slider_set_value(ui_SliderHeater, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderHeater) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderHeater, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderHeater, 150);
    lv_obj_set_height(ui_SliderHeater, 4);
    lv_obj_set_x(ui_SliderHeater, -65);
    lv_obj_set_y(ui_SliderHeater, -196);
    lv_obj_set_align(ui_SliderHeater, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderHeater, lv_color_hex(0xFA9F10), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderHeater, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderHeater, lv_color_hex(0xFF0202), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderHeater, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderHeater, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderHeater, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderHeater, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderHeater, 6, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderLiving = lv_slider_create(ui_PanelLED);
    lv_slider_set_range(ui_SliderLiving, 20, 100);
    lv_slider_set_value(ui_SliderLiving, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderLiving) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderLiving, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderLiving, 150);
    lv_obj_set_height(ui_SliderLiving, 4);
    lv_obj_set_x(ui_SliderLiving, 136);
    lv_obj_set_y(ui_SliderLiving, -196);
    lv_obj_set_align(ui_SliderLiving, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderLiving, lv_color_hex(0xFA9F10), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLiving, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderLiving, lv_color_hex(0xFF0202), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderLiving, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderLiving, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderLiving, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderLiving, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderLiving, 6, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_heaterButton = lv_btn_create(ui_PanelLED);
    lv_obj_set_width(ui_heaterButton, 114);
    lv_obj_set_height(ui_heaterButton, 60);
    lv_obj_set_x(ui_heaterButton, -65);
    lv_obj_set_y(ui_heaterButton, -144);
    lv_obj_set_align(ui_heaterButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_heaterButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_heaterButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_heaterButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_heaterButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_heaterButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_heaterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_heaterButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_heaterButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_heaterButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_heaterButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image17 = lv_img_create(ui_heaterButton);
    lv_img_set_src(ui_Image17, &ui_img_140505863);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, -28);
    lv_obj_set_y(ui_Image17, 0);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label48 = lv_label_create(ui_heaterButton);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 21);
    lv_obj_set_y(ui_Label48, -1);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "히 터");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_livingButton = lv_btn_create(ui_PanelLED);
    lv_obj_set_width(ui_livingButton, 114);
    lv_obj_set_height(ui_livingButton, 60);
    lv_obj_set_x(ui_livingButton, 136);
    lv_obj_set_y(ui_livingButton, -144);
    lv_obj_set_align(ui_livingButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_livingButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_livingButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_livingButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_livingButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_livingButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_livingButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_livingButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_livingButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_livingButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_livingButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image18 = lv_img_create(ui_livingButton);
    lv_img_set_src(ui_Image18, &ui_img_213141187);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image18, -28);
    lv_obj_set_y(ui_Image18, 0);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_livingButton);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, 21);
    lv_obj_set_y(ui_Label44, -1);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "거 실");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelOUT = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelOUT, 140);
    lv_obj_set_height(ui_PanelOUT, 434);
    lv_obj_set_x(ui_PanelOUT, 328);
    lv_obj_set_y(ui_PanelOUT, 21);
    lv_obj_set_align(ui_PanelOUT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelOUT, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PanelOUT, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_PanelOUT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelOUT, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelOUT, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOUT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelOUT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelOUT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelOUT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelOUT, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelOUT, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bunkerButton = lv_btn_create(ui_PanelOUT);
    lv_obj_set_width(ui_bunkerButton, 114);
    lv_obj_set_height(ui_bunkerButton, 60);
    lv_obj_set_x(ui_bunkerButton, 138);
    lv_obj_set_y(ui_bunkerButton, -158);
    lv_obj_set_align(ui_bunkerButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_bunkerButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_bunkerButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_bunkerButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_bunkerButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_bunkerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_bunkerButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_bunkerButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_bunkerButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bunkerButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_bunkerButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image16 = lv_img_create(ui_bunkerButton);
    lv_img_set_src(ui_Image16, &ui_img_213141187);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, -32);
    lv_obj_set_y(ui_Image16, 0);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image16, 220);

    ui_Label30 = lv_label_create(ui_bunkerButton);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 15);
    lv_obj_set_y(ui_Label30, 0);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "벙 커");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outButton2 = lv_btn_create(ui_PanelOUT);
    lv_obj_set_width(ui_outButton2, 114);
    lv_obj_set_height(ui_outButton2, 60);
    lv_obj_set_x(ui_outButton2, 131);
    lv_obj_set_y(ui_outButton2, 0);
    lv_obj_set_align(ui_outButton2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outButton2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_outButton2, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_outButton2, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_outButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_outButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_outButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_outButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_outButton2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outButton2, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_outButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image11 = lv_img_create(ui_outButton2);
    lv_img_set_src(ui_Image11, &ui_img_969258056);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -37);
    lv_obj_set_y(ui_Image11, 0);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 180);

    ui_outLabel2 = lv_label_create(ui_outButton2);
    lv_obj_set_width(ui_outLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outLabel2, 15);
    lv_obj_set_y(ui_outLabel2, 0);
    lv_obj_set_align(ui_outLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outLabel2, "물펌프");
    lv_obj_set_style_text_color(ui_outLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel2, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outButton3 = lv_btn_create(ui_PanelOUT);
    lv_obj_set_width(ui_outButton3, 114);
    lv_obj_set_height(ui_outButton3, 60);
    lv_obj_set_x(ui_outButton3, 131);
    lv_obj_set_y(ui_outButton3, 0);
    lv_obj_set_align(ui_outButton3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outButton3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_outButton3, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_outButton3, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_outButton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_outButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_outButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_outButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_outButton3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outButton3, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_outButton3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image12 = lv_img_create(ui_outButton3);
    lv_img_set_src(ui_Image12, &ui_img_199453633);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image12, -37);
    lv_obj_set_y(ui_Image12, 0);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 200);

    ui_outLabel3 = lv_label_create(ui_outButton3);
    lv_obj_set_width(ui_outLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outLabel3, 15);
    lv_obj_set_y(ui_outLabel3, 0);
    lv_obj_set_align(ui_outLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outLabel3, "맥스팬");
    lv_obj_set_style_text_color(ui_outLabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel3, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outButton4 = lv_btn_create(ui_PanelOUT);
    lv_obj_set_width(ui_outButton4, 114);
    lv_obj_set_height(ui_outButton4, 60);
    lv_obj_set_x(ui_outButton4, 183);
    lv_obj_set_y(ui_outButton4, -1);
    lv_obj_set_align(ui_outButton4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outButton4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_outButton4, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_outButton4, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_outButton4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_outButton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_outButton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_outButton4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_outButton4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outButton4, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_outButton4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image13 = lv_img_create(ui_outButton4);
    lv_img_set_src(ui_Image13, &ui_img_199452608);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image13, -37);
    lv_obj_set_y(ui_Image13, 0);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image13, 200);

    ui_outLabel4 = lv_label_create(ui_outButton4);
    lv_obj_set_width(ui_outLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outLabel4, 15);
    lv_obj_set_y(ui_outLabel4, 0);
    lv_obj_set_align(ui_outLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outLabel4, "전기실\n팬");
    lv_obj_set_style_text_color(ui_outLabel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_outLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel4, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_boilerButton = lv_btn_create(ui_PanelOUT);
    lv_obj_set_width(ui_boilerButton, 114);
    lv_obj_set_height(ui_boilerButton, 60);
    lv_obj_set_x(ui_boilerButton, 131);
    lv_obj_set_y(ui_boilerButton, 0);
    lv_obj_set_align(ui_boilerButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_boilerButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_boilerButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_boilerButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_boilerButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_boilerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_boilerButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_boilerButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_boilerButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_boilerButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_boilerButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image14 = lv_img_create(ui_boilerButton);
    lv_img_set_src(ui_Image14, &ui_img_2077020016);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image14, -37);
    lv_obj_set_y(ui_Image14, 0);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image14, 200);

    ui_outLabel5 = lv_label_create(ui_boilerButton);
    lv_obj_set_width(ui_outLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outLabel5, 15);
    lv_obj_set_y(ui_outLabel5, 0);
    lv_obj_set_align(ui_outLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outLabel5, "보일러");
    lv_obj_set_style_text_color(ui_outLabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel5, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outButton6 = lv_btn_create(ui_PanelOUT);
    lv_obj_set_width(ui_outButton6, 114);
    lv_obj_set_height(ui_outButton6, 60);
    lv_obj_set_x(ui_outButton6, 19);
    lv_obj_set_y(ui_outButton6, -76);
    lv_obj_set_align(ui_outButton6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outButton6, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_outButton6, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_outButton6, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_outButton6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_outButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_outButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_outButton6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_outButton6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outButton6, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_outButton6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image15 = lv_img_create(ui_outButton6);
    lv_img_set_src(ui_Image15, &ui_img_1190290745);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, -37);
    lv_obj_set_y(ui_Image15, 0);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image15, 250);

    ui_Label29 = lv_label_create(ui_outButton6);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 15);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "냉장고");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 383);
    lv_obj_set_height(ui_Container5, 316);
    lv_obj_set_x(ui_Container5, 45);
    lv_obj_set_y(ui_Container5, 75);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button1, 90);
    lv_obj_set_height(ui_Button1, 90);
    lv_obj_set_x(ui_Button1, -125);
    lv_obj_set_y(ui_Button1, -105);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button1, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button1, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button1, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image6 = lv_img_create(ui_Button1);
    lv_img_set_src(ui_Image6, &ui_img_199447235);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -20);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 250);

    ui_ledLabel1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_ledLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledLabel1, 0);
    lv_obj_set_y(ui_ledLabel1, 20);
    lv_obj_set_align(ui_ledLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledLabel1, "실내등");
    lv_obj_set_style_text_color(ui_ledLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ledLabel1, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button2, 90);
    lv_obj_set_height(ui_Button2, 90);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -105);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button2, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button2, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button2, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image1 = lv_img_create(ui_Button2);
    lv_img_set_src(ui_Image1, &ui_img_1965946780);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -16);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 400);

    ui_ledLabel2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_ledLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledLabel2, 0);
    lv_obj_set_y(ui_ledLabel2, 20);
    lv_obj_set_align(ui_ledLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledLabel2, "간접등");
    lv_obj_set_style_text_color(ui_ledLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ledLabel2, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button3, 90);
    lv_obj_set_height(ui_Button3, 90);
    lv_obj_set_x(ui_Button3, 125);
    lv_obj_set_y(ui_Button3, -105);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button3, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button3, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button3, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image2 = lv_img_create(ui_Button3);
    lv_img_set_src(ui_Image2, &ui_img_912627908);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -18);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 250);

    ui_ledLabel3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_ledLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledLabel3, 0);
    lv_obj_set_y(ui_ledLabel3, 20);
    lv_obj_set_align(ui_ledLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledLabel3, "주방등");
    lv_obj_set_style_text_color(ui_ledLabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ledLabel3, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button4, 90);
    lv_obj_set_height(ui_Button4, 90);
    lv_obj_set_x(ui_Button4, -125);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button4, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button4, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button4, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image5 = lv_img_create(ui_Button4);
    lv_img_set_src(ui_Image5, &ui_img_1965946780);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 0);
    lv_obj_set_y(ui_Image5, -19);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 400);

    ui_ledLabel4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_ledLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledLabel4, 0);
    lv_obj_set_y(ui_ledLabel4, 20);
    lv_obj_set_align(ui_ledLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledLabel4, "벙커등");
    lv_obj_set_style_text_color(ui_ledLabel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ledLabel4, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button5, 90);
    lv_obj_set_height(ui_Button5, 90);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button5, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button5, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button5, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image7 = lv_img_create(ui_Button5);
    lv_img_set_src(ui_Image7, &ui_img_2077021041);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -18);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 250);

    ui_ledLabel5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_ledLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledLabel5, 0);
    lv_obj_set_y(ui_ledLabel5, 20);
    lv_obj_set_align(ui_ledLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledLabel5, "욕실등");
    lv_obj_set_style_text_color(ui_ledLabel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ledLabel5, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button6, 90);
    lv_obj_set_height(ui_Button6, 90);
    lv_obj_set_x(ui_Button6, 125);
    lv_obj_set_y(ui_Button6, 0);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button6, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button6, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image8 = lv_img_create(ui_Button6);
    lv_img_set_src(ui_Image8, &ui_img_1543939845);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, -18);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 400);

    ui_ledLabel6 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_ledLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ledLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ledLabel6, 0);
    lv_obj_set_y(ui_ledLabel6, 20);
    lv_obj_set_align(ui_ledLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ledLabel6, "어닝등");
    lv_obj_set_style_text_color(ui_ledLabel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ledLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ledLabel6, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outButton1 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_outButton1, 90);
    lv_obj_set_height(ui_outButton1, 90);
    lv_obj_set_x(ui_outButton1, 0);
    lv_obj_set_y(ui_outButton1, 105);
    lv_obj_set_align(ui_outButton1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outButton1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_outButton1, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_outButton1, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_outButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_outButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_outButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_outButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_outButton1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outButton1, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_outButton1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image9 = lv_img_create(ui_outButton1);
    lv_img_set_src(ui_Image9, &ui_img_1965946780);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 0);
    lv_obj_set_y(ui_Image9, -20);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 400);

    ui_outLabel1 = lv_label_create(ui_outButton1);
    lv_obj_set_width(ui_outLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outLabel1, 0);
    lv_obj_set_y(ui_outLabel1, 20);
    lv_obj_set_align(ui_outLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outLabel1, "현관등");
    lv_obj_set_style_text_color(ui_outLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outLabel1, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_Button7, 90);
    lv_obj_set_height(ui_Button7, 90);
    lv_obj_set_x(ui_Button7, -125);
    lv_obj_set_y(ui_Button7, 105);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button7, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Button7, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Button7, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_Button7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image10 = lv_img_create(ui_Button7);
    lv_img_set_src(ui_Image10, &ui_img_1543932672);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, -20);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 220);

    ui_Label15 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 20);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "전체등");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_invButton = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_invButton, 90);
    lv_obj_set_height(ui_invButton, 90);
    lv_obj_set_x(ui_invButton, 125);
    lv_obj_set_y(ui_invButton, 105);
    lv_obj_set_align(ui_invButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_invButton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_invButton, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_invButton, LV_DIR_LEFT);
    lv_obj_set_style_radius(ui_invButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_invButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_invButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_invButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_invButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_invButton, lv_color_hex(0xFA9F10), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_invButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image19 = lv_img_create(ui_invButton);
    lv_img_set_src(ui_Image19, &ui_img_1294863193);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image19, 0);
    lv_obj_set_y(ui_Image19, -20);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image19, 250);

    ui_Label333 = lv_label_create(ui_invButton);
    lv_obj_set_width(ui_Label333, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label333, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label333, 0);
    lv_obj_set_y(ui_Label333, 20);
    lv_obj_set_align(ui_Label333, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label333, "인버터");
    lv_obj_set_style_text_color(ui_Label333, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label333, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label333, &ui_font_SOYOMapleBold22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImageWiFi, ui_event_ImageWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelDay, ui_event_LabelDay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container3, ui_event_Container3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clnButton, ui_event_clnButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wstButton, ui_event_wstButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempDownButton, ui_event_tempDownButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempUpButton, ui_event_tempUpButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderHeater, ui_event_SliderHeater, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderLiving, ui_event_SliderLiving, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_heaterButton, ui_event_heaterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_livingButton, ui_event_livingButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bunkerButton, ui_event_bunkerButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outButton2, ui_event_outButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outButton3, ui_event_outButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outButton4, ui_event_outButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_boilerButton, ui_event_boilerButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outButton6, ui_event_outButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outButton1, ui_event_outButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_invButton, ui_event_invButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);

}
